<?php

return [
    'phq9' => ['Bir şeyler yapmaya karşı az ilgi veya zevk', 'Kendini üzgün, çökkün veya umutsuz hissetme', 'Uykuya dalmakta ya da uyumaya devam etmekte güçlük ya da çok fazla uyuma', 'Yorgun hissetme veya az enerji', 'İştahsızlık veya aşırı yeme', 'Kendiniz hakkında kötü hissetme ya da başarısız olduğunuzu düşünme', 'Konsantre olmakta güçlük', 'Başkalarının fark edeceği kadar yavaş hareket etme/konuşma ya da huzursuzluk', 'Ölmüş olsanız daha iyi olacağı ya da kendinize zarar verme düşünceleri'],
    'gad7' => ['Sinirli, kaygılı veya gergin hissetme', 'Endişelenmeyi durduramama veya kontrol edememe', 'Farklı şeyler hakkında çok fazla endişelenme', 'Gevşemekte güçlük', 'Yerinde duramayacak kadar huzursuz olma', 'Kolayca sinirlenme veya alınganlık', 'Kötü bir şey olacakmış gibi korkma'],
    'pss10' => ['Beklenmedik bir şey yüzünden üzülme', 'Hayatınızdaki önemli şeyleri kontrol edemediğinizi hissetme', 'Sinirli ve stresli hissetme', 'Kişisel sorunları çözme yeteneğinize güvenme', 'İşlerin istediğiniz gibi gittiğini hissetme', 'Yapmanız gereken her şeyle başa çıkamama', 'Hayatınızdaki sıkıntıları kontrol edebilme', 'Her şeyin üstesinden geldiğinizi hissetme', 'Kontrolünüz dışındaki şeyler yüzünden öfkelenme', 'Zorlukların üstesinden gelemeyecek kadar biriktiğini hissetme'],
    'isi' => ['Uykuya dalmakta güçlük', 'Uykuyu sürdürmekte güçlük', 'Çok erken uyanma', 'Mevcut uyku düzeninizden ne kadar memnunsunuz?', 'Uyku sorununuz başkaları için ne kadar fark edilir?', 'Uyku sorununuz hakkında ne kadar endişelisiniz?', 'Uyku sorununuz günlük işlevselliğinizi ne kadar etkiliyor?'],
    'pcl5' => ['Stresli deneyimle ilgili tekrarlayan rahatsız edici anılar', 'Tekrarlayan rahatsız edici rüyalar', 'Aniden yeniden yaşanıyormuş gibi hissetme veya davranma', 'Hatırlatıldığında çok üzülme', 'Hatırlatıldığında güçlü bedensel tepkiler', 'Anılardan, düşüncelerden veya duygulardan kaçınma', 'Dış hatırlatıcılardan kaçınma', 'Önemli kısımları hatırlamakta güçlük', 'Kendiniz, başkaları veya dünya hakkında güçlü olumsuz inançlar', 'Kendinizi veya başkalarını suçlama', 'Güçlü olumsuz duygular', 'Etkinliklere ilgi kaybı', 'Uzak veya kopuk hissetme', 'Olumlu duyguları yaşamakta güçlük', 'Sinirli davranış veya öfke patlamaları', 'Çok fazla risk alma', 'Aşırı tetikte olma', 'Kolayca irkilme', 'Konsantrasyon güçlüğü', 'Uykuya dalmakta veya sürdürmekte güçlük'],
    'audit_c' => ['Ne sıklıkla alkollü içecek içersiniz?', 'İçtiğiniz tipik bir günde kaç kadeh içersiniz?', 'Ne sıklıkla bir seferde altı veya daha fazla kadeh içersiniz?'],
];
