"""Shared vocabulary for the behavior-signal catalog.

Every ``possible_context`` referenced by a signal must exist here so the UI can
render a consistent bilingual label and so reviewers can audit the full list of
benign / non-clinical explanations the system is allowed to surface.
"""

# key -> (english, persian)
CONTEXTS = {
    # --- environment / technical ---
    "camera_placement": ("camera placement or angle", "زاویه یا محل قرارگیری دوربین"),
    "screen_placement": ("screen placement", "محل قرارگیری صفحه‌نمایش"),
    "lighting": ("lighting conditions", "شرایط نور محیط"),
    "screen_use": ("screen use / reading on screen", "استفاده از صفحه‌نمایش یا خواندن از روی آن"),
    "reading": ("reading notes or messages", "خواندن یادداشت یا پیام"),
    "other_person": ("another person or pet in the room", "حضور فرد یا حیوان دیگری در اتاق"),
    "noise": ("environmental noise", "سر و صدای محیط"),
    "network_latency": ("network / audio delay", "تأخیر شبکه یا صدا"),
    "device_handling": ("adjusting device, camera or headset", "تنظیم دستگاه، دوربین یا هدست"),
    "microphone": ("microphone distance or gain", "فاصله یا حساسیت میکروفون"),
    "temperature": ("room temperature", "دمای اتاق"),
    "chair": ("chair ergonomics / discomfort", "ارگونومی یا ناراحتی صندلی"),
    "clothing": ("clothing or accessories", "لباس یا زیورآلات"),
    "glasses": ("glasses, reflections or mask", "عینک، انعکاس نور یا ماسک"),
    "privacy_need": ("temporary privacy need", "نیاز موقت به حریم خصوصی"),
    # --- physical / bodily ---
    "fatigue": ("fatigue or sleepiness", "خستگی یا خواب‌آلودگی"),
    "physical_discomfort": ("physical discomfort or pain", "ناراحتی جسمی یا درد"),
    "itching": ("itching or skin irritation", "خارش یا تحریک پوست"),
    "dry_eyes": ("dry or irritated eyes", "خشکی یا تحریک چشم"),
    "illness": ("cold, allergy or other physical illness", "سرماخوردگی، آلرژی یا بیماری جسمی"),
    "medication": ("medication side effects", "عوارض دارویی"),
    "neurological": ("neurological or musculoskeletal factors (medical review)", "عوامل عصبی یا اسکلتی‌عضلانی (نیازمند بررسی پزشکی)"),
    "caffeine": ("caffeine, nicotine or stimulants", "کافئین، نیکوتین یا محرک‌ها"),
    "hunger_thirst": ("hunger, thirst or need for a break", "گرسنگی، تشنگی یا نیاز به استراحت"),
    "breathing": ("breathing pattern / respiratory factors", "الگوی تنفس یا عوامل تنفسی"),
    "hearing": ("hearing difficulty", "مشکل شنوایی"),
    "vision": ("vision difficulty", "مشکل بینایی"),
    "posture_habit": ("habitual posture", "عادت وضعیتی بدن"),
    "stretching": ("stretching or repositioning", "کشش یا تغییر وضعیت"),
    # --- cognitive / conversational ---
    "thinking": ("thinking or reflecting", "فکر کردن یا تأمل"),
    "word_finding": ("word finding / formulating an answer", "جست‌وجوی واژه یا فرمول‌بندی پاسخ"),
    "cognitive_effort": ("cognitive effort / concentration", "تلاش شناختی یا تمرکز"),
    "memory_retrieval": ("recalling events", "یادآوری رویدادها"),
    "distraction": ("distraction", "حواس‌پرتی"),
    "boredom": ("boredom or low interest in topic", "بی‌حوصلگی یا علاقه کم به موضوع"),
    "engagement": ("engagement or interest", "درگیری یا علاقه"),
    "speech_emphasis": ("speech emphasis", "تأکید گفتاری"),
    "conversational_feedback": ("conversational feedback (backchannel)", "بازخورد گفت‌وگویی"),
    "acknowledgment": ("acknowledgment", "تأیید دریافت پیام"),
    "agreement": ("agreement", "موافقت"),
    "disagreement": ("disagreement", "مخالفت"),
    "humor": ("humor or social smile", "شوخی یا لبخند اجتماعی"),
    "politeness": ("politeness / social convention", "ادب یا عرف اجتماعی"),
    "cultural_norm": ("cultural or individual communication norm", "هنجار فرهنگی یا فردی ارتباط"),
    "communication_style": ("individual communication style", "سبک ارتباطی فردی"),
    "language": ("language or accent effects", "اثر زبان یا لهجه"),
    "question_type": ("type of question (open vs closed)", "نوع سؤال (باز یا بسته)"),
    "topic": ("topic of conversation", "موضوع گفت‌وگو"),
    "topic_familiarity": ("familiarity with the topic", "آشنایی با موضوع"),
    "topic_related": ("topic-associated response (correlation, not causation)", "پاسخ مرتبط با موضوع (هم‌زمانی، نه علیت)"),
    "coincidence": ("coincidence", "تصادف"),
    "habit": ("personal habit or mannerism", "عادت یا خصوصیت شخصی"),
    "self_soothing": ("self-soothing or self-regulation", "خودآرام‌سازی یا خودتنظیمی"),
    "restlessness": ("restlessness", "بی‌قراری"),
    "emotional_response": ("emotional response (unspecified)", "واکنش هیجانی (نامشخص)"),
    "affective_expression": ("affective expression (unspecified)", "ابراز عاطفی (نامشخص)"),
    "activation": ("increased activation / energy", "افزایش برانگیختگی یا انرژی"),
    "low_energy": ("reduced energy", "کاهش انرژی"),
    "discomfort_with_topic": ("discomfort with the topic", "ناراحتی با موضوع"),
    "relief": ("relief or relaxation", "آسودگی یا آرامش"),
    "surprise": ("surprise", "شگفتی"),
    "confusion": ("confusion / not understanding", "سردرگمی یا نفهمیدن"),
    "interaction_change": ("change in interaction dynamics", "تغییر در پویایی تعامل"),
    "rapport": ("rapport / connection with clinician", "ارتباط و همدلی با درمانگر"),
    "urgency": ("urgency to speak", "عجله برای صحبت"),
    "session_phase": ("session phase (start / end effects)", "مرحله جلسه (اثر شروع یا پایان)"),
    "object_manipulation": ("manipulating an object (pen, phone)", "بازی با شیء (خودکار، گوشی)"),
    "music": ("music or rhythm in environment", "موسیقی یا ریتم در محیط"),
    "self_support": ("self-support / comfort posture", "وضعیت حمایتی یا راحتی"),
    "camera_framing": ("camera framing hiding body parts", "کادر دوربین که بخشی از بدن را پنهان می‌کند"),
    "technical_issue": ("technical issue", "مشکل فنی"),
    "interruption": ("external interruption", "وقفه بیرونی"),
    "explicit_content": ("explicit verbal content (review transcript)", "محتوای صریح کلامی (متن مکالمه را بررسی کنید)"),
    "figure_of_speech": ("figure of speech / idiom", "اصطلاح یا کنایه زبانی"),
    "asr_error": ("speech-recognition error", "خطای تشخیص گفتار"),
}


# Display tiers control how prominently an event is shown to the clinician.
TIERS = {
    "quality": ("Quality / technical flag", "پرچم کیفیت یا فنی"),
    "observation": ("Observation (low salience)", "مشاهده (اهمیت کم)"),
    "change": ("Change from baseline", "تغییر نسبت به خط پایه"),
    "cluster": ("Multimodal cluster", "خوشه چندوجهی"),
    "content": ("Verbal content flag", "پرچم محتوای کلامی"),
    "medical": ("Consider physical / medical explanation", "احتمال توضیح جسمی یا پزشکی"),
    "safety": ("Safety-relevant verbal content (clinician review now)", "محتوای کلامی مرتبط با ایمنی (بررسی فوری درمانگر)"),
}
