"""Face, head, eye, brow and mouth signals."""

from signal_helpers import S

R_HEAD = ("Head orientation and motion are commonly recorded in mental-status observation as part of "
          "attention, engagement and psychomotor description. Changes are only meaningful relative to the "
          "same person's baseline and the conversational moment.",
          "جهت و حرکت سر در توصیف وضعیت روانی به‌عنوان بخشی از توجه، درگیری و توصیف روانی‌حرکتی ثبت می‌شود. "
          "تغییر فقط نسبت به خط پایه همان فرد و لحظه گفت‌وگو معنا دارد.")
R_GAZE = ("Gaze behaviour is part of standard observation of eye contact and attention, but it is strongly "
          "shaped by culture, screen layout, and thinking style; on video, 'eye contact' is only a proxy.",
          "رفتار نگاه بخشی از مشاهده استاندارد تماس چشمی و توجه است، اما به‌شدت تحت تأثیر فرهنگ، چیدمان صفحه و سبک تفکر است؛ در ویدئو، «تماس چشمی» تنها یک نماینده است.")
R_BLINK = ("Blink rate varies with screen use, dryness, lighting and cognitive load; within-person changes "
           "may accompany shifts in attention or arousal but are nonspecific.",
           "نرخ پلک با استفاده از صفحه، خشکی چشم، نور و بار شناختی تغییر می‌کند؛ تغییرات درون‌فردی ممکن است با تغییر توجه یا برانگیختگی همراه باشد اما غیراختصاصی است.")
R_EXPR = ("Facial movement described via FACS action units is descriptive, not emotional. Reduced or increased "
          "facial expressiveness relative to baseline is something clinicians already observe qualitatively.",
          "حرکت چهره بر اساس واحدهای حرکتی FACS توصیفی است، نه هیجانی. کاهش یا افزایش بیان چهره نسبت به خط پایه چیزی است که درمانگران به‌صورت کیفی مشاهده می‌کنند.")

SIGNALS = [
    # ------------------------------------------------------------------ head
    S("head_turn_away_sustained", "face_head",
      "Head held turned away from the screen for a sustained period",
      "سر برای مدتی طولانی از صفحه برگردانده شده است",
      ["head_yaw", "head_pitch"], ["other_person", "noise", "screen_placement", "reading", "thinking", "distraction"],
      detector="sustained", threshold=25, min_duration_s=6, rationale_en=R_HEAD[0], rationale_fa=R_HEAD[1],
      note_en="Check environmental explanations first.", note_fa="ابتدا توضیح‌های محیطی را بررسی کنید."),
    S("head_turn_rate_change", "face_head",
      "Frequency of head turns away changed from baseline",
      "تعداد برگرداندن سر نسبت به خط پایه تغییر کرده است",
      ["head_yaw", "head_angular_velocity"], ["other_person", "distraction", "cognitive_effort", "restlessness"],
      tier="change", detector="rate_change", rationale_en=R_HEAD[0], rationale_fa=R_HEAD[1]),
    S("head_down_sustained", "face_head",
      "Head held in a downward orientation for a sustained period",
      "سر برای مدتی طولانی رو به پایین نگه داشته شده است",
      ["head_pitch", "neck_flexion"], ["reading", "fatigue", "posture_habit", "emotional_response", "screen_placement"],
      detector="sustained", threshold=-18, direction="down", min_duration_s=10, rationale_en=R_HEAD[0], rationale_fa=R_HEAD[1],
      note_en="Downward head orientation must not be mapped to sadness or depression.",
      note_fa="جهت رو به پایین سر نباید به غم یا افسردگی نگاشت شود."),
    S("head_up_sustained", "face_head",
      "Head/chin held elevated for a sustained period",
      "سر یا چانه برای مدتی طولانی بالا نگه داشته شده است",
      ["head_pitch"], ["screen_placement", "posture_habit", "stretching", "thinking"],
      detector="sustained", threshold=15, direction="up", min_duration_s=8, rationale_en=R_HEAD[0], rationale_fa=R_HEAD[1]),
    S("head_tilt_lateral_sustained", "face_head",
      "Sustained lateral head tilt",
      "کج شدن جانبی سر به‌صورت پایدار",
      ["head_roll"], ["posture_habit", "engagement", "thinking", "camera_placement", "neurological"],
      detector="sustained", threshold=12, min_duration_s=10, rationale_en=R_HEAD[0], rationale_fa=R_HEAD[1]),
    S("head_nod_event", "face_head",
      "Head nod (vertical oscillation) events",
      "سر تکان دادن عمودی (تأیید)",
      ["head_pitch", "head_angular_velocity"], ["acknowledgment", "agreement", "conversational_feedback", "habit"],
      detector="periodicity", band=(0.8, 4.0), min_duration_s=0.6, gates=("face",), rationale_en=R_HEAD[0], rationale_fa=R_HEAD[1],
      note_en="Do not equate nodding with true agreement.", note_fa="سر تکان دادن را با موافقت واقعی برابر نگیرید."),
    S("head_shake_event", "face_head",
      "Horizontal head-shake events",
      "سر تکان دادن افقی (نفی)",
      ["head_yaw", "head_angular_velocity"], ["disagreement", "speech_emphasis", "habit"],
      detector="periodicity", band=(0.8, 4.0), min_duration_s=0.6, rationale_en=R_HEAD[0], rationale_fa=R_HEAD[1],
      note_en="Interpret with speech content.", note_fa="همراه با محتوای گفتار تفسیر شود."),
    S("head_nod_rate_change", "face_head",
      "Rate of nodding changed from baseline",
      "نرخ سر تکان دادن نسبت به خط پایه تغییر کرده است",
      ["head_pitch"], ["conversational_feedback", "engagement", "interaction_change", "habit"],
      tier="change", detector="rate_change", rationale_en=R_HEAD[0], rationale_fa=R_HEAD[1]),
    S("head_stillness_increase", "face_head",
      "Head motion markedly reduced compared with baseline",
      "حرکت سر نسبت به خط پایه به‌طور محسوس کاهش یافته است",
      ["head_motion_energy", "stillness_duration"], ["thinking", "fatigue", "low_energy", "engagement", "technical_issue"],
      tier="change", direction="down", threshold=-2.0, window_s=60, rationale_en=R_HEAD[0], rationale_fa=R_HEAD[1],
      note_en="Verify the video is not frozen before surfacing.", note_fa="پیش از نمایش، بررسی کنید ویدئو فریز نشده باشد."),
    S("head_motion_increase", "face_head",
      "Head motion increased compared with baseline",
      "حرکت سر نسبت به خط پایه افزایش یافته است",
      ["head_motion_energy", "head_angular_velocity"], ["speech_emphasis", "restlessness", "activation", "distraction", "device_handling"],
      tier="change", direction="up", window_s=60, rationale_en=R_HEAD[0], rationale_fa=R_HEAD[1]),
    S("head_jerk_event", "face_head",
      "Sudden rapid head movement",
      "حرکت ناگهانی و سریع سر",
      ["head_angular_velocity"], ["noise", "interruption", "surprise", "habit", "neurological"],
      detector="event", threshold=180, rationale_en=R_HEAD[0], rationale_fa=R_HEAD[1]),
    S("head_bob_rhythmic", "face_head",
      "Rhythmic head bobbing not aligned with speech",
      "تکان ریتمیک سر بدون هم‌زمانی با گفتار",
      ["head_pitch", "head_roll"], ["music", "habit", "self_soothing", "restlessness", "neurological"],
      detector="periodicity", band=(0.3, 3.0), min_duration_s=6, rationale_en=R_HEAD[0], rationale_fa=R_HEAD[1]),
    S("head_toward_camera", "face_head",
      "Head moved closer to the camera",
      "سر به دوربین نزدیک‌تر شده است",
      ["head_scale", "head_tx", "head_ty"], ["screen_use", "vision", "hearing", "engagement", "device_handling"],
      tier="change", direction="up", threshold=2.0, window_s=20, rationale_en=R_HEAD[0], rationale_fa=R_HEAD[1]),
    S("head_withdrawal", "face_head",
      "Head moved away from the camera",
      "سر از دوربین دور شده است",
      ["head_scale"], ["chair", "stretching", "relief", "discomfort_with_topic", "device_handling"],
      tier="change", direction="down", threshold=-2.0, window_s=20, rationale_en=R_HEAD[0], rationale_fa=R_HEAD[1]),
    S("head_pose_variability_change", "face_head",
      "Variability of head orientation changed from baseline",
      "تغییرپذیری جهت سر نسبت به خط پایه تغییر کرده است",
      ["head_yaw", "head_pitch", "head_roll"], ["cognitive_effort", "restlessness", "engagement", "fatigue"],
      tier="change", window_s=60, rationale_en=R_HEAD[0], rationale_fa=R_HEAD[1]),
    S("head_orientation_to_screen_ratio_change", "face_head",
      "Share of time the head is oriented toward the screen changed",
      "سهم زمانی که سر رو به صفحه است تغییر کرده است",
      ["head_yaw", "head_pitch"], ["other_person", "distraction", "reading", "engagement", "screen_placement"],
      tier="change", window_s=120, rationale_en=R_HEAD[0], rationale_fa=R_HEAD[1]),

    # ------------------------------------------------------------------ gaze
    S("gaze_away_sustained", "eyes_gaze",
      "Sustained gaze away from screen/camera",
      "نگاه به مدت طولانی از صفحه یا دوربین دور است",
      ["gaze_x", "gaze_y", "gaze_on_screen", "head_yaw"], ["thinking", "reading", "distraction", "cultural_norm", "camera_placement", "discomfort_with_topic"],
      detector="sustained", threshold=0.45, min_duration_s=5, rationale_en=R_GAZE[0], rationale_fa=R_GAZE[1],
      note_en="Nonspecific. Never label as avoidance, deception or anxiety.", note_fa="غیراختصاصی. هرگز به‌عنوان اجتناب، فریب یا اضطراب برچسب نزنید."),
    S("gaze_shift_rate_change", "eyes_gaze",
      "Frequency of gaze shifts changed from baseline",
      "تعداد جابه‌جایی نگاه نسبت به خط پایه تغییر کرده است",
      ["gaze_shift_event"], ["distraction", "cognitive_effort", "communication_style", "screen_use"],
      tier="change", detector="rate_change", rationale_en=R_GAZE[0], rationale_fa=R_GAZE[1]),
    S("gaze_down_sustained", "eyes_gaze",
      "Sustained downward gaze with head relatively still",
      "نگاه پایدار رو به پایین با سر نسبتاً ثابت",
      ["gaze_y", "head_pitch"], ["reading", "thinking", "memory_retrieval", "emotional_response", "screen_placement"],
      detector="sustained", threshold=-0.35, direction="down", min_duration_s=6, rationale_en=R_GAZE[0], rationale_fa=R_GAZE[1]),
    S("gaze_up_sustained", "eyes_gaze",
      "Sustained upward gaze",
      "نگاه پایدار رو به بالا",
      ["gaze_y"], ["thinking", "memory_retrieval", "screen_placement", "other_person"],
      detector="sustained", threshold=0.35, direction="up", min_duration_s=5, rationale_en=R_GAZE[0], rationale_fa=R_GAZE[1]),
    S("gaze_lateral_sustained", "eyes_gaze",
      "Sustained lateral gaze",
      "نگاه پایدار به یک سمت",
      ["gaze_x"], ["other_person", "reading", "thinking", "screen_placement"],
      detector="sustained", threshold=0.4, min_duration_s=5, rationale_en=R_GAZE[0], rationale_fa=R_GAZE[1]),
    S("gaze_fixation_long", "eyes_gaze",
      "Unusually long fixation with minimal blinking",
      "تثبیت نگاه بسیار طولانی با پلک زدن اندک",
      ["gaze_fixation_duration", "blink_event"], ["thinking", "fatigue", "engagement", "screen_use", "medication"],
      detector="sustained", threshold=12, min_duration_s=12, rationale_en=R_GAZE[0], rationale_fa=R_GAZE[1]),
    S("gaze_scanning_increase", "eyes_gaze",
      "Rapid scanning gaze pattern (high saccade rate)",
      "الگوی نگاه پویشی سریع",
      ["gaze_shift_event", "gaze_fixation_duration"], ["reading", "distraction", "other_person", "restlessness", "activation"],
      tier="change", detector="rate_change", threshold=2.2, rationale_en=R_GAZE[0], rationale_fa=R_GAZE[1]),
    S("gaze_to_camera_ratio_change", "eyes_gaze",
      "Share of gaze toward the camera changed from baseline",
      "سهم نگاه به دوربین نسبت به خط پایه تغییر کرده است",
      ["gaze_on_camera"], ["cultural_norm", "engagement", "thinking", "screen_placement", "discomfort_with_topic"],
      tier="change", window_s=120, rationale_en=R_GAZE[0], rationale_fa=R_GAZE[1]),
    S("gaze_speaking_vs_listening_shift", "eyes_gaze",
      "Gaze-to-camera during own speech differs markedly from during listening",
      "نگاه به دوربین هنگام صحبت با هنگام گوش دادن تفاوت محسوس دارد",
      ["gaze_on_camera", "speaker"], ["communication_style", "cultural_norm", "thinking", "word_finding"],
      comparison="vs_own_speaking_vs_listening", window_s=180, rationale_en=R_GAZE[0], rationale_fa=R_GAZE[1]),
    S("gaze_to_self_view_pattern", "eyes_gaze",
      "Gaze repeatedly directed at the self-view region of the screen",
      "نگاه مکرر به ناحیه تصویر خود روی صفحه",
      ["gaze_x", "gaze_y"], ["screen_use", "habit", "device_handling", "emotional_response"],
      detector="rate_change", threshold=2.0, rationale_en=R_GAZE[0], rationale_fa=R_GAZE[1],
      note_en="Requires known screen layout; low precision.", note_fa="نیازمند دانستن چیدمان صفحه؛ دقت پایین."),

    # ------------------------------------------------------------------ blink / lids
    S("blink_rate_increase", "eyes_gaze",
      "Blink rate increased relative to baseline",
      "نرخ پلک زدن نسبت به خط پایه افزایش یافته است",
      ["blink_event", "ear_left", "ear_right"], ["dry_eyes", "screen_use", "lighting", "fatigue", "activation", "cognitive_effort"],
      tier="change", detector="rate_change", threshold=1.7, rationale_en=R_BLINK[0], rationale_fa=R_BLINK[1]),
    S("blink_rate_decrease", "eyes_gaze",
      "Blink rate decreased relative to baseline",
      "نرخ پلک زدن نسبت به خط پایه کاهش یافته است",
      ["blink_event"], ["screen_use", "cognitive_effort", "engagement", "medication", "fatigue"],
      tier="change", detector="rate_change", threshold=0.5, direction="down", rationale_en=R_BLINK[0], rationale_fa=R_BLINK[1]),
    S("blink_burst", "eyes_gaze",
      "Burst of rapid successive blinks",
      "رگبار پلک زدن‌های سریع پیاپی",
      ["blink_event"], ["dry_eyes", "lighting", "surprise", "activation", "habit"],
      detector="event", threshold=4, window_s=3, rationale_en=R_BLINK[0], rationale_fa=R_BLINK[1]),
    S("blink_duration_long", "eyes_gaze",
      "Blink durations longer than baseline",
      "مدت پلک زدن طولانی‌تر از خط پایه",
      ["blink_duration"], ["fatigue", "medication", "dry_eyes", "thinking"],
      tier="change", direction="up", rationale_en=R_BLINK[0], rationale_fa=R_BLINK[1]),
    S("eye_closure_long", "eyes_gaze",
      "Eyes closed for a prolonged period",
      "چشم‌ها برای مدت طولانی بسته مانده‌اند",
      ["eye_closure_duration"], ["fatigue", "thinking", "dry_eyes", "emotional_response", "medication"],
      detector="sustained", threshold=2.0, min_duration_s=2.0, rationale_en=R_BLINK[0], rationale_fa=R_BLINK[1],
      note_en="Do not infer sleepiness or distress without corroboration.", note_fa="بدون شواهد تکمیلی، خواب‌آلودگی یا پریشانی استنباط نشود."),
    S("partial_eye_closure_sustained", "eyes_gaze",
      "Eye aperture reduced (drooping lids) relative to baseline",
      "باز بودن چشم‌ها نسبت به خط پایه کاهش یافته (افتادگی پلک)",
      ["eye_aperture_mean"], ["fatigue", "lighting", "medication", "illness", "neurological"],
      tier="change", direction="down", threshold=-2.0, window_s=45, rationale_en=R_BLINK[0], rationale_fa=R_BLINK[1]),
    S("eye_widening_event", "eyes_gaze",
      "Brief widening of the eyes (upper lid raise)",
      "گشاد شدن کوتاه چشم‌ها",
      ["eye_aperture_mean"], ["surprise", "speech_emphasis", "lighting", "affective_expression"],
      detector="event", threshold=1.5, window_s=2, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("eye_squint_sustained", "eyes_gaze",
      "Sustained narrowing of the eyes",
      "تنگ شدن پایدار چشم‌ها",
      ["eye_aperture_mean", "brow_distance"], ["lighting", "vision", "cognitive_effort", "affective_expression", "glasses"],
      detector="sustained", threshold=-1.5, direction="down", min_duration_s=5, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("eye_asymmetry_sustained", "eyes_gaze",
      "Persistent asymmetry of eye opening",
      "عدم تقارن پایدار در باز بودن چشم‌ها",
      ["eye_asymmetry"], ["camera_placement", "lighting", "posture_habit", "neurological"],
      tier="medical", detector="sustained", threshold=0.25, min_duration_s=30, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1],
      note_en="Quality/medical flag only; may reflect angle or pre-existing feature.", note_fa="صرفاً پرچم کیفیت/پزشکی؛ ممکن است ناشی از زاویه یا ویژگی قبلی باشد."),
    S("iris_oscillation_like", "eyes_gaze",
      "Rhythmic micro-oscillation of iris position detected",
      "نوسان ریز و ریتمیک موقعیت مردمک",
      ["iris_oscillation_hz"], ["technical_issue", "lighting", "neurological", "medication"],
      tier="medical", detector="periodicity", band=(2.0, 8.0), min_duration_s=3, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1],
      note_en="Very low reliability on webcams (needs >=30 fps); route to medical review, never interpret psychologically.",
      note_fa="اعتماد بسیار کم روی وب‌کم (نیازمند ۳۰ فریم بر ثانیه یا بیشتر)؛ برای بررسی پزشکی، هرگز تفسیر روان‌شناختی نشود."),
    S("eye_rub_event", "eyes_gaze",
      "Hand contact with eye region",
      "تماس دست با ناحیه چشم",
      ["hand_region_contact", "hand_face_distance_left", "hand_face_distance_right"], ["dry_eyes", "fatigue", "itching", "emotional_response", "habit"],
      detector="event", gates=("face", "hands"), rationale_en=R_BLINK[0], rationale_fa=R_BLINK[1]),
    S("tearing_like_visual_change", "eyes_gaze",
      "Increased specular reflection in eye region (possible tearing)",
      "افزایش بازتاب نور در ناحیه چشم (احتمال اشک)",
      ["illumination", "eye_aperture_mean"], ["lighting", "dry_eyes", "illness", "emotional_response"],
      tier="observation", detector="level_change", threshold=2.5, window_s=20, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1],
      note_en="Experimental, low reliability. Surface only with high face quality and never as 'crying'.",
      note_fa="آزمایشی با اعتماد پایین. فقط با کیفیت بالای چهره نمایش داده شود و هرگز به‌عنوان «گریه» برچسب نخورد."),

    # ------------------------------------------------------------------ brows
    S("brow_raise_event", "brow_forehead",
      "Brow raise (inner/outer brow elevation)",
      "بالا رفتن ابرو",
      ["brow_height_left", "brow_height_right"], ["speech_emphasis", "surprise", "conversational_feedback", "confusion"],
      detector="event", threshold=1.2, window_s=2, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("brow_raise_rate_change", "brow_forehead",
      "Rate of brow raises changed from baseline",
      "نرخ بالا رفتن ابرو نسبت به خط پایه تغییر کرده است",
      ["brow_height_left", "brow_height_right"], ["speech_emphasis", "communication_style", "engagement", "affective_expression"],
      tier="change", detector="rate_change", rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("brow_lower_sustained", "brow_forehead",
      "Sustained brow lowering / furrow",
      "پایین آمدن یا گره خوردن پایدار ابرو",
      ["brow_distance", "brow_height_left", "brow_height_right"], ["cognitive_effort", "lighting", "vision", "affective_expression", "physical_discomfort"],
      detector="sustained", threshold=-1.2, direction="down", min_duration_s=4, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("brow_furrow_rate_change", "brow_forehead",
      "Frequency of brow furrowing changed from baseline",
      "تعداد گره خوردن ابرو نسبت به خط پایه تغییر کرده است",
      ["brow_distance"], ["cognitive_effort", "confusion", "affective_expression", "lighting"],
      tier="change", detector="rate_change", rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("brow_inner_raise_sustained", "brow_forehead",
      "Sustained inner-brow raise (AU1) with outer brows level",
      "بالا رفتن پایدار بخش داخلی ابرو",
      ["brow_height_left", "brow_height_right", "brow_distance"], ["affective_expression", "cognitive_effort", "habit", "speech_emphasis"],
      detector="sustained", threshold=1.0, min_duration_s=3, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1],
      note_en="Describe the movement; do not assign sadness/worry.", note_fa="حرکت را توصیف کنید؛ غم یا نگرانی نسبت ندهید."),
    S("brow_asymmetry_event", "brow_forehead",
      "Unilateral brow raise",
      "بالا رفتن یک‌طرفه ابرو",
      ["brow_asymmetry"], ["speech_emphasis", "habit", "communication_style", "affective_expression"],
      detector="event", threshold=1.0, window_s=2, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("brow_flash_event", "brow_forehead",
      "Very brief brow raise (<0.5 s)",
      "بالا رفتن بسیار کوتاه ابرو",
      ["brow_height_left", "brow_height_right"], ["acknowledgment", "conversational_feedback", "surprise", "habit"],
      detector="event", threshold=1.0, window_s=1, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),

    # ------------------------------------------------------------------ mouth / lips / jaw
    S("lip_press_sustained", "mouth_lips_jaw",
      "Lips pressed together for a sustained period (AU23/24-like)",
      "فشردن پایدار لب‌ها روی هم",
      ["lip_thickness", "mar"], ["thinking", "habit", "cognitive_effort", "affective_expression", "speech_emphasis"],
      detector="sustained", threshold=-1.2, direction="down", min_duration_s=3, speaker_state="patient_listening",
      rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("lip_press_rate_change", "mouth_lips_jaw",
      "Frequency of lip pressing changed from baseline",
      "تعداد فشردن لب نسبت به خط پایه تغییر کرده است",
      ["lip_thickness"], ["habit", "cognitive_effort", "affective_expression", "physical_discomfort"],
      tier="change", detector="rate_change", rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("lip_corner_pull_event", "mouth_lips_jaw",
      "Lip corner pull (smile-like, AU12)",
      "کشیده شدن گوشه لب (شبه‌لبخند)",
      ["mouth_corner_angle", "mouth_width"], ["humor", "politeness", "conversational_feedback", "affective_expression", "speech_emphasis"],
      detector="event", threshold=1.0, window_s=3, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("smile_rate_change", "mouth_lips_jaw",
      "Smile frequency changed from baseline",
      "تعداد لبخند نسبت به خط پایه تغییر کرده است",
      ["mouth_corner_angle"], ["humor", "politeness", "topic", "rapport", "affective_expression", "interaction_change"],
      tier="change", detector="rate_change", rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("smile_duration_change", "mouth_lips_jaw",
      "Average smile duration changed from baseline",
      "میانگین مدت لبخند نسبت به خط پایه تغییر کرده است",
      ["mouth_corner_angle"], ["humor", "politeness", "communication_style", "affective_expression"],
      tier="change", rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("smile_with_cheek_raise", "mouth_lips_jaw",
      "Smile accompanied by cheek raise / eye narrowing (AU6+AU12)",
      "لبخند همراه با بالا رفتن گونه و تنگ شدن چشم",
      ["mouth_corner_angle", "eye_aperture_mean"], ["humor", "rapport", "affective_expression", "lighting"],
      detector="event", threshold=1.0, window_s=3, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1],
      note_en="Descriptive co-activation only; never claim a smile is 'genuine' or 'fake'.",
      note_fa="فقط توصیف هم‌فعالی است؛ هرگز ادعا نشود لبخند «واقعی» یا «ساختگی» است."),
    S("smile_without_cheek_raise_ratio_change", "mouth_lips_jaw",
      "Proportion of smiles without cheek involvement changed",
      "نسبت لبخندهای بدون درگیری گونه تغییر کرده است",
      ["mouth_corner_angle", "eye_aperture_mean"], ["politeness", "communication_style", "lighting", "affective_expression"],
      tier="change", window_s=180, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1],
      note_en="Descriptive only; culturally variable.", note_fa="فقط توصیفی؛ وابسته به فرهنگ."),
    S("smile_asymmetry_sustained", "mouth_lips_jaw",
      "Persistent asymmetric smile",
      "لبخند نامتقارن پایدار",
      ["smile_symmetry"], ["habit", "camera_placement", "communication_style", "neurological"],
      tier="medical", detector="sustained", threshold=0.3, min_duration_s=2, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("lip_corner_depress_event", "mouth_lips_jaw",
      "Lip corners pulled downward (AU15)",
      "پایین کشیده شدن گوشه‌های لب",
      ["mouth_corner_angle"], ["speech_emphasis", "thinking", "affective_expression", "habit"],
      detector="event", threshold=1.0, window_s=3, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("lip_corner_depress_sustained", "mouth_lips_jaw",
      "Lip corners held downward for a sustained period",
      "پایین ماندن پایدار گوشه‌های لب",
      ["mouth_corner_angle"], ["posture_habit", "affective_expression", "fatigue", "camera_placement"],
      detector="sustained", threshold=-1.0, direction="down", min_duration_s=8, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("lip_pucker_event", "mouth_lips_jaw",
      "Lip pucker / funnel (AU18/22)",
      "غنچه کردن لب",
      ["mouth_width", "mar"], ["thinking", "speech_emphasis", "habit"],
      detector="event", threshold=1.0, window_s=3, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("lip_bite_like_event", "mouth_lips_jaw",
      "Lip drawn inward / bite-like (AU28/32)",
      "گاز گرفتن یا داخل کشیدن لب",
      ["lip_thickness", "mar"], ["habit", "thinking", "dry_eyes", "self_soothing"],
      detector="event", threshold=1.0, window_s=3, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("lip_bite_rate_change", "mouth_lips_jaw",
      "Rate of lip biting changed from baseline",
      "نرخ گاز گرفتن لب نسبت به خط پایه تغییر کرده است",
      ["lip_thickness"], ["habit", "self_soothing", "cognitive_effort"],
      tier="change", detector="rate_change", rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("mouth_open_rest_sustained", "mouth_lips_jaw",
      "Mouth held open while not speaking",
      "باز ماندن دهان در حالت غیرگفتاری",
      ["mar"], ["breathing", "illness", "fatigue", "surprise", "habit"],
      detector="sustained", threshold=0.25, min_duration_s=6, speaker_state="patient_listening", rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("jaw_lateral_movement_event", "mouth_lips_jaw",
      "Lateral jaw movement (AU30)",
      "حرکت جانبی فک",
      ["jaw_lateral"], ["habit", "physical_discomfort", "thinking", "medication"],
      detector="event", threshold=1.0, window_s=3, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("jaw_clench_like_sustained", "mouth_lips_jaw",
      "Lips pressed with jaw held rigid (clench-like)",
      "فشردن لب‌ها با فک سفت (شبیه دندان‌قروچه)",
      ["lip_thickness", "face_landmark_motion_energy"], ["habit", "physical_discomfort", "cognitive_effort", "affective_expression"],
      detector="sustained", threshold=-1.2, direction="down", min_duration_s=6, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1],
      note_en="Masseter is not visible; this is a lip/jaw geometry proxy.", note_fa="عضله فک دیده نمی‌شود؛ این یک نماینده هندسی لب/فک است."),
    S("mouth_stretch_event", "mouth_lips_jaw",
      "Horizontal mouth stretch (AU20)",
      "کشیده شدن افقی دهان",
      ["mouth_width"], ["speech_emphasis", "affective_expression", "habit"],
      detector="event", threshold=1.0, window_s=3, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("lip_tremor_like", "mouth_lips_jaw",
      "High-frequency oscillation of lip landmarks",
      "نوسان ریز و سریع نقاط لب",
      ["lip_oscillation_hz"], ["temperature", "emotional_response", "neurological", "medication", "technical_issue"],
      tier="medical", detector="periodicity", band=(4.0, 10.0), min_duration_s=2, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1],
      note_en="Needs >=25 fps and stable face quality.", note_fa="نیازمند ۲۵ فریم بر ثانیه و کیفیت پایدار چهره."),
    S("tongue_show_event", "mouth_lips_jaw",
      "Tongue visible (AU19)",
      "نمایان شدن زبان",
      ["mar"], ["habit", "humor", "speech_emphasis", "medication"],
      detector="event", threshold=1.0, window_s=3, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("yawn_like_event", "mouth_lips_jaw",
      "Wide, slow mouth opening (yawn-like)",
      "باز شدن گسترده و آهسته دهان (شبیه خمیازه)",
      ["mar", "eye_aperture_mean"], ["fatigue", "boredom", "breathing", "session_phase"],
      detector="event", threshold=0.6, window_s=6, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("chin_raise_event", "mouth_lips_jaw",
      "Chin raise / lower-lip push (AU17)",
      "بالا دادن چانه",
      ["lip_thickness", "mouth_corner_angle"], ["thinking", "speech_emphasis", "habit", "affective_expression"],
      detector="event", threshold=1.0, window_s=3, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("cheek_raise_event", "mouth_lips_jaw",
      "Cheek raise (AU6)",
      "بالا رفتن گونه",
      ["eye_aperture_mean"], ["humor", "lighting", "vision", "affective_expression"],
      detector="event", threshold=1.0, window_s=3, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("nose_wrinkle_event", "mouth_lips_jaw",
      "Nose wrinkle (AU9)",
      "چین افتادن بینی",
      ["face_landmark_motion_energy"], ["itching", "illness", "speech_emphasis", "affective_expression"],
      detector="event", threshold=1.0, window_s=3, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("swallow_like_event", "mouth_lips_jaw",
      "Throat/chin motion consistent with swallowing",
      "حرکت چانه/گلو سازگار با بلع",
      ["face_landmark_motion_energy", "neck_flexion"], ["hunger_thirst", "illness", "speech_emphasis", "habit"],
      detector="event", threshold=1.0, window_s=3, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1],
      note_en="Low reliability; requires neck visible.", note_fa="اعتماد پایین؛ نیازمند دیده شدن گردن."),

    # ------------------------------------------------------------------ expression dynamics
    S("expressiveness_decrease", "facial_expression_dynamics",
      "Overall facial movement reduced relative to baseline",
      "حرکت کلی چهره نسبت به خط پایه کاهش یافته است",
      ["au_activity_total", "face_landmark_motion_energy"], ["fatigue", "low_energy", "thinking", "medication", "lighting", "cultural_norm"],
      tier="change", direction="down", threshold=-2.0, window_s=90, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1],
      note_en="Descriptive 'reduced expressiveness'; never 'flat affect' as a label.", note_fa="فقط «کاهش بیان چهره»؛ هرگز برچسب «عاطفه سطحی» زده نشود."),
    S("expressiveness_increase", "facial_expression_dynamics",
      "Overall facial movement increased relative to baseline",
      "حرکت کلی چهره نسبت به خط پایه افزایش یافته است",
      ["au_activity_total"], ["speech_emphasis", "humor", "activation", "engagement", "topic"],
      tier="change", direction="up", window_s=90, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("expression_variability_change", "facial_expression_dynamics",
      "Variability of facial activity changed from baseline",
      "تغییرپذیری فعالیت چهره نسبت به خط پایه تغییر کرده است",
      ["au_activity_variance"], ["topic", "communication_style", "fatigue", "engagement"],
      tier="change", window_s=120, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("brief_facial_movement_event", "facial_expression_dynamics",
      "Brief (<0.5 s) facial movement burst",
      "حرکت بسیار کوتاه چهره (کمتر از نیم ثانیه)",
      ["au_activity_total"], ["speech_emphasis", "habit", "affective_expression", "technical_issue"],
      detector="event", threshold=2.0, window_s=1, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1],
      note_en="Never label as 'micro-expression' of a hidden emotion; scientific support is weak.",
      note_fa="هرگز به‌عنوان «ریزحالت» هیجان پنهان برچسب نخورد؛ پشتوانه علمی ضعیف است."),
    S("expression_onset_latency_change", "facial_expression_dynamics",
      "Latency of facial response after clinician question changed",
      "تأخیر پاسخ چهره‌ای پس از سؤال درمانگر تغییر کرده است",
      ["expression_onset_latency", "question_event"], ["thinking", "network_latency", "question_type", "fatigue"],
      tier="change", window_s=300, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("facial_asymmetry_sustained", "facial_expression_dynamics",
      "Persistent global facial asymmetry",
      "عدم تقارن پایدار کل چهره",
      ["face_asymmetry_index"], ["camera_placement", "lighting", "neurological", "habit"],
      tier="medical", detector="sustained", threshold=0.3, min_duration_s=60, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1],
      note_en="Medical/quality flag. Not a psychological inference.", note_fa="پرچم پزشکی/کیفیت. استنباط روان‌شناختی نیست."),
    S("expression_persistence_long", "facial_expression_dynamics",
      "A facial configuration held unusually long",
      "یک حالت چهره به‌طور غیرمعمول طولانی حفظ شده است",
      ["au_activity_total", "au_activity_variance"], ["thinking", "fatigue", "politeness", "affective_expression"],
      detector="sustained", threshold=1.0, min_duration_s=10, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("neutral_face_ratio_change", "facial_expression_dynamics",
      "Share of time with near-neutral face changed from baseline",
      "سهم زمان چهره خنثی نسبت به خط پایه تغییر کرده است",
      ["au_activity_total"], ["fatigue", "cultural_norm", "topic", "thinking"],
      tier="change", window_s=180, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("facial_activity_during_listening_change", "facial_expression_dynamics",
      "Facial activity while listening changed from baseline",
      "فعالیت چهره هنگام گوش دادن نسبت به خط پایه تغییر کرده است",
      ["au_activity_total", "speaker"], ["engagement", "fatigue", "conversational_feedback", "topic"],
      tier="change", speaker_state="patient_listening", window_s=120, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
    S("facial_activity_during_speaking_change", "facial_expression_dynamics",
      "Facial activity while speaking changed from baseline",
      "فعالیت چهره هنگام صحبت نسبت به خط پایه تغییر کرده است",
      ["au_activity_total", "speaker"], ["speech_emphasis", "topic", "fatigue", "activation"],
      tier="change", speaker_state="patient_speaking", window_s=120, rationale_en=R_EXPR[0], rationale_fa=R_EXPR[1]),
]
