"""Posture, shoulders/neck, hands/arms, self-adaptors, gestures, lower body and whole-body motion."""

from signal_helpers import S

R_POST = ("Posture and gross motor activity are part of the classic 'appearance and behaviour' and "
          "'psychomotor activity' sections of a mental-status observation. Video lets these be described "
          "quantitatively, but chair, camera and habit explain most variance.",
          "وضعیت بدن و فعالیت حرکتی درشت بخشی از قسمت‌های کلاسیک «ظاهر و رفتار» و «فعالیت روانی‌حرکتی» در مشاهده وضعیت روانی هستند. "
          "ویدئو امکان توصیف کمی آن‌ها را می‌دهد، اما صندلی، دوربین و عادت بیشتر واریانس را توضیح می‌دهند.")
R_ADAPT = ("Self-touch ('self-adaptor') behaviours are common in everyday conversation and rise with itching, "
           "cognitive load, fatigue and self-regulation alike. Only within-person rate changes near a specific "
           "moment are informative, and only as a prompt to the clinician.",
           "رفتارهای خودلمسی در گفت‌وگوی روزمره رایج‌اند و با خارش، بار شناختی، خستگی و خودتنظیمی به یک اندازه افزایش می‌یابند. "
           "فقط تغییر نرخ درون‌فردی در نزدیکی یک لحظه مشخص اطلاع‌رسان است، و فقط به‌عنوان یادآور برای درمانگر.")
R_GEST = ("Co-speech gesture rate and amplitude track engagement, emphasis and cultural style; reduction or "
          "increase relative to baseline is descriptive of psychomotor activity, not of any diagnosis.",
          "نرخ و دامنه ژست‌های هم‌زمان با گفتار با درگیری، تأکید و سبک فرهنگی هم‌بسته است؛ کاهش یا افزایش نسبت به خط پایه توصیف فعالیت روانی‌حرکتی است، نه تشخیص.")
R_MOTOR = ("Rhythmic or repetitive limb movements are usually habit or restlessness; some patterns warrant a "
           "physical/medication review, which is why they are routed as medical flags rather than "
           "psychological observations.",
           "حرکات ریتمیک یا تکراری اندام‌ها معمولاً عادت یا بی‌قراری هستند؛ برخی الگوها نیازمند بررسی جسمی/دارویی‌اند و به همین دلیل به‌عنوان پرچم پزشکی و نه مشاهده روان‌شناختی مسیریابی می‌شوند.")

SIGNALS = [
    # ------------------------------------------------------------------ torso posture
    S("lean_forward", "upper_body_posture",
      "Torso moved/held forward relative to baseline",
      "تنه نسبت به خط پایه به جلو متمایل شده است",
      ["torso_angle", "body_scale"], ["screen_use", "engagement", "hearing", "vision", "posture_habit"],
      tier="change", detector="level_change", gates=("pose",), direction="up", window_s=20, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("lean_back", "upper_body_posture",
      "Torso moved/held backward relative to baseline",
      "تنه نسبت به خط پایه به عقب متمایل شده است",
      ["torso_angle", "body_scale"], ["chair", "relief", "interaction_change", "stretching", "posture_habit"],
      tier="change", gates=("pose",), direction="down", window_s=20, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("slumped_posture_sustained", "upper_body_posture",
      "Sustained reduction in upright torso angle",
      "کاهش پایدار زاویه راست بودن تنه (خمیدگی)",
      ["torso_angle", "neck_flexion", "shoulder_width_ratio"], ["fatigue", "chair", "posture_habit", "physical_discomfort", "low_energy"],
      detector="sustained", gates=("pose",), threshold=-1.5, direction="down", min_duration_s=30, rationale_en=R_POST[0], rationale_fa=R_POST[1],
      note_en="Do not map to depression or low mood.", note_fa="به افسردگی یا خلق پایین نگاشت نشود."),
    S("upright_posture_increase", "upper_body_posture",
      "Torso became more upright than baseline",
      "تنه نسبت به خط پایه راست‌تر شده است",
      ["torso_angle", "neck_flexion"], ["engagement", "activation", "stretching", "device_handling"],
      tier="change", gates=("pose",), direction="up", window_s=30, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("posture_collapse_event", "upper_body_posture",
      "Sudden drop into a slumped position",
      "افت ناگهانی به وضعیت خمیده",
      ["torso_angle", "pose_delta"], ["relief", "fatigue", "chair", "emotional_response", "stretching"],
      detector="event", gates=("pose",), threshold=1.0, window_s=3, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("posture_change_rate_increase", "upper_body_posture",
      "Meaningful posture changes more frequent than baseline",
      "تغییرات معنادار وضعیت بدن بیشتر از خط پایه شده است",
      ["pose_change_event", "pose_delta"], ["restlessness", "physical_discomfort", "chair", "activation", "topic_related"],
      tier="change", detector="rate_change", gates=("pose",), rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("posture_change_rate_decrease", "upper_body_posture",
      "Meaningful posture changes less frequent than baseline",
      "تغییرات معنادار وضعیت بدن کمتر از خط پایه شده است",
      ["pose_change_event"], ["thinking", "fatigue", "engagement", "low_energy", "technical_issue"],
      tier="change", detector="rate_change", gates=("pose",), threshold=0.45, direction="down", rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("postural_stillness_episode", "upper_body_posture",
      "Extended period with almost no body movement",
      "دوره طولانی تقریباً بدون حرکت بدن",
      ["stillness_duration", "motion_energy_total"], ["thinking", "engagement", "fatigue", "technical_issue", "low_energy"],
      detector="sustained", gates=("pose",), threshold=45, min_duration_s=45, rationale_en=R_POST[0], rationale_fa=R_POST[1],
      note_en="Verify video is live (frame counter) before surfacing.", note_fa="پیش از نمایش، زنده بودن ویدئو را بررسی کنید."),
    S("torso_turn_away", "upper_body_posture",
      "Torso rotated away from the camera",
      "تنه از دوربین چرخیده است",
      ["torso_yaw"], ["device_handling", "other_person", "distraction", "chair", "stretching"],
      detector="sustained", gates=("pose",), threshold=30, min_duration_s=6, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("torso_sway_rhythmic", "upper_body_posture",
      "Rhythmic forward/back or lateral torso sway (rocking-like)",
      "نوسان ریتمیک تنه به جلو/عقب یا جانبی (شبیه تاب خوردن)",
      ["torso_oscillation_hz", "torso_angle", "torso_lateral_angle"], ["music", "chair", "self_soothing", "habit", "restlessness"],
      detector="periodicity", gates=("pose",), band=(0.2, 2.0), min_duration_s=8, rationale_en=R_MOTOR[0], rationale_fa=R_MOTOR[1]),
    S("torso_sway_increase", "upper_body_posture",
      "Non-rhythmic torso sway increased from baseline",
      "نوسان غیرریتمیک تنه نسبت به خط پایه افزایش یافته است",
      ["torso_angle", "torso_lateral_angle"], ["chair", "restlessness", "fatigue", "speech_emphasis"],
      tier="change", gates=("pose",), window_s=60, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("lateral_lean_sustained", "upper_body_posture",
      "Sustained lean to one side",
      "تمایل پایدار به یک سمت",
      ["torso_lateral_angle"], ["chair", "self_support", "posture_habit", "physical_discomfort", "camera_placement"],
      detector="sustained", gates=("pose",), threshold=12, min_duration_s=20, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("body_off_center_sustained", "upper_body_posture",
      "Body positioned off-center in frame for a sustained period",
      "بدن برای مدتی طولانی خارج از مرکز کادر قرار دارد",
      ["body_center_x", "body_center_y"], ["camera_placement", "chair", "other_person", "privacy_need"],
      tier="quality", detector="sustained", gates=("pose",), threshold=0.3, min_duration_s=20, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("body_distance_change", "upper_body_posture",
      "Distance from camera changed markedly",
      "فاصله از دوربین به‌طور محسوس تغییر کرده است",
      ["body_scale", "head_scale"], ["device_handling", "chair", "engagement", "relief", "screen_use"],
      tier="change", gates=("pose",), window_s=20, rationale_en=R_POST[0], rationale_fa=R_POST[1]),

    # ------------------------------------------------------------------ shoulders / neck
    S("shoulder_asymmetry_sustained", "shoulders_neck",
      "Persistent shoulder height/rotation asymmetry",
      "عدم تقارن پایدار ارتفاع یا چرخش شانه‌ها",
      ["shoulder_asymmetry"], ["camera_placement", "posture_habit", "self_support", "neurological"],
      tier="quality", detector="sustained", gates=("pose",), threshold=0.08, min_duration_s=60, rationale_en=R_POST[0], rationale_fa=R_POST[1],
      note_en="Primarily a quality/context flag.", note_fa="عمدتاً پرچم کیفیت/زمینه است."),
    S("shoulder_elevation_sustained", "shoulders_neck",
      "Shoulders held elevated toward the ears",
      "شانه‌ها به سمت گوش‌ها بالا نگه داشته شده‌اند",
      ["shoulder_neck_distance"], ["temperature", "chair", "physical_discomfort", "posture_habit", "affective_expression"],
      detector="sustained", gates=("pose",), threshold=-1.5, direction="down", min_duration_s=15, rationale_en=R_POST[0], rationale_fa=R_POST[1],
      note_en="Do not label as anxiety or tension.", note_fa="به‌عنوان اضطراب یا تنش برچسب نخورد."),
    S("shoulder_raise_repeated", "shoulders_neck",
      "Repeated shoulder elevation events",
      "بالا بردن مکرر شانه‌ها",
      ["shoulder_neck_distance"], ["stretching", "physical_discomfort", "speech_emphasis", "habit"],
      tier="change", detector="rate_change", gates=("pose",), rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("shoulder_shrug_event", "shoulders_neck",
      "Brief bilateral shoulder shrug",
      "بالا انداختن کوتاه دو شانه",
      ["shoulder_neck_distance"], ["speech_emphasis", "confusion", "communication_style", "habit"],
      detector="event", gates=("pose",), threshold=1.0, window_s=2, rationale_en=R_GEST[0], rationale_fa=R_GEST[1]),
    S("shoulder_forward_rounding", "shoulders_neck",
      "Shoulders rounded forward relative to baseline",
      "شانه‌ها نسبت به خط پایه به جلو گرد شده‌اند",
      ["shoulder_width_ratio", "torso_angle"], ["chair", "posture_habit", "fatigue", "screen_use", "temperature"],
      tier="change", gates=("pose",), direction="down", window_s=60, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("shoulder_drop_event", "shoulders_neck",
      "Sudden shoulder drop (exhalation-like release)",
      "افت ناگهانی شانه‌ها (شبیه رهاسازی همراه بازدم)",
      ["shoulder_neck_distance", "pose_delta"], ["relief", "breathing", "fatigue", "stretching", "emotional_response"],
      detector="event", gates=("pose",), threshold=1.0, window_s=3, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("neck_flexion_sustained", "shoulders_neck",
      "Neck flexed forward for a sustained period",
      "گردن برای مدتی طولانی به جلو خم شده است",
      ["neck_flexion"], ["screen_use", "reading", "posture_habit", "fatigue", "physical_discomfort"],
      detector="sustained", gates=("pose",), threshold=25, min_duration_s=20, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("neck_extension_sustained", "shoulders_neck",
      "Neck extended backward for a sustained period",
      "گردن برای مدتی طولانی به عقب کشیده شده است",
      ["neck_flexion"], ["stretching", "chair", "thinking", "physical_discomfort"],
      detector="sustained", gates=("pose",), threshold=-15, direction="down", min_duration_s=10, rationale_en=R_POST[0], rationale_fa=R_POST[1]),

    # ------------------------------------------------------------------ arms
    S("arms_crossed_sustained", "hands_arms",
      "Arms crossed for a sustained period",
      "دست‌ها برای مدتی طولانی روی سینه جمع شده‌اند",
      ["arms_crossed_score"], ["temperature", "self_support", "habit", "chair", "posture_habit"],
      detector="sustained", gates=("pose",), threshold=0.7, min_duration_s=20, rationale_en=R_POST[0], rationale_fa=R_POST[1],
      note_en="Never infer defensiveness or closedness.", note_fa="هرگز حالت تدافعی یا بسته بودن استنباط نشود."),
    S("arms_crossed_onset", "hands_arms",
      "Arms became crossed shortly after a question/topic change",
      "دست‌ها اندکی پس از سؤال یا تغییر موضوع جمع شدند",
      ["arms_crossed_score", "question_event"], ["temperature", "self_support", "coincidence", "topic_related", "habit"],
      detector="event", gates=("pose",), threshold=0.7, window_s=10, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("arms_uncrossed_onset", "hands_arms",
      "Arms opened from a crossed position",
      "دست‌ها از حالت جمع‌شده باز شدند",
      ["arms_crossed_score"], ["speech_emphasis", "relief", "stretching", "device_handling"],
      detector="event", gates=("pose",), threshold=0.7, window_s=10, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("self_hug_arm_rub", "hands_arms",
      "Hand holding/rubbing opposite arm",
      "گرفتن یا مالیدن بازوی مخالف با دست",
      ["hand_region_contact", "hand_contact_duration"], ["temperature", "self_soothing", "itching", "habit", "physical_discomfort"],
      detector="sustained", gates=("pose", "hands"), threshold=1, min_duration_s=5, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("arm_rest_position_change", "hands_arms",
      "Resting position of arms changed (lap / desk / armrest)",
      "محل قرار گرفتن دست‌ها تغییر کرده است (پا / میز / دسته صندلی)",
      ["pose_change_event", "hand_velocity_left", "hand_velocity_right"], ["chair", "stretching", "device_handling", "interaction_change"],
      detector="event", gates=("pose",), threshold=1, window_s=5, rationale_en=R_POST[0], rationale_fa=R_POST[1]),

    # ------------------------------------------------------------------ hand-to-body (self-adaptors)
    S("hand_to_face_event", "hands_arms",
      "Hand contact or near-contact with the face",
      "تماس یا نزدیک شدن دست به صورت",
      ["hand_face_distance_left", "hand_face_distance_right", "hand_region_contact"], ["itching", "thinking", "habit", "self_soothing", "self_support"],
      detector="event", gates=("face", "hands"), threshold=1, window_s=5, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("hand_to_face_rate_change", "hands_arms",
      "Frequency of hand-to-face contact changed from baseline",
      "تعداد تماس دست با صورت نسبت به خط پایه تغییر کرده است",
      ["hand_contact_event", "hand_region_contact"], ["itching", "thinking", "habit", "self_soothing", "topic_related", "fatigue"],
      tier="change", detector="rate_change", gates=("face", "hands"), rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("hand_to_mouth", "hands_arms",
      "Hand covering or touching the mouth",
      "دست روی دهان یا در تماس با آن",
      ["hand_region_contact"], ["thinking", "habit", "illness", "self_soothing", "politeness"],
      detector="event", gates=("face", "hands"), threshold=1, window_s=5, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("hand_to_mouth_while_speaking", "hands_arms",
      "Hand near mouth while the patient is speaking",
      "دست نزدیک دهان هنگام صحبت بیمار",
      ["hand_region_contact", "speaker"], ["habit", "politeness", "thinking", "self_soothing"],
      detector="sustained", gates=("face", "hands"), threshold=1, min_duration_s=3, speaker_state="patient_speaking", rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1],
      note_en="Also lowers ASR quality; treat partly as a quality flag.", note_fa="کیفیت تشخیص گفتار را هم کاهش می‌دهد؛ تا حدی پرچم کیفیت است."),
    S("hand_to_nose", "hands_arms",
      "Hand touching the nose",
      "تماس دست با بینی",
      ["hand_region_contact"], ["itching", "illness", "habit", "thinking"],
      detector="event", gates=("face", "hands"), threshold=1, window_s=5, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1],
      note_en="Nose-touching has no validated link to deception.", note_fa="لمس بینی هیچ ارتباط معتبری با فریب ندارد."),
    S("hand_to_forehead_temple", "hands_arms",
      "Hand on forehead or temple",
      "دست روی پیشانی یا شقیقه",
      ["hand_region_contact"], ["thinking", "physical_discomfort", "fatigue", "self_support", "habit"],
      detector="event", gates=("face", "hands"), threshold=1, window_s=5, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("hand_to_hair", "hands_arms",
      "Hand touching, twirling or pulling hair",
      "لمس، پیچاندن یا کشیدن مو با دست",
      ["hand_region_contact", "hand_contact_duration"], ["habit", "self_soothing", "clothing", "itching"],
      detector="event", gates=("face", "hands"), threshold=1, window_s=5, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("hand_to_hair_rate_change", "hands_arms",
      "Hair-touching frequency changed from baseline",
      "تعداد لمس مو نسبت به خط پایه تغییر کرده است",
      ["hand_region_contact"], ["habit", "self_soothing", "topic_related", "restlessness"],
      tier="change", detector="rate_change", gates=("face", "hands"), rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("hand_to_neck", "hands_arms",
      "Hand touching the neck or collar",
      "تماس دست با گردن یا یقه",
      ["hand_region_contact"], ["clothing", "itching", "habit", "physical_discomfort", "self_soothing"],
      detector="event", gates=("pose", "hands"), threshold=1, window_s=5, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("hand_to_ear", "hands_arms",
      "Hand touching the ear or earpiece",
      "تماس دست با گوش یا هندزفری",
      ["hand_region_contact"], ["device_handling", "hearing", "itching", "habit"],
      detector="event", gates=("face", "hands"), threshold=1, window_s=5, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("hand_to_chest", "hands_arms",
      "Hand placed on the chest",
      "قرار دادن دست روی سینه",
      ["hand_region_contact"], ["speech_emphasis", "breathing", "physical_discomfort", "self_soothing", "clothing"],
      detector="event", gates=("pose", "hands"), threshold=1, window_s=5, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("hand_to_abdomen", "hands_arms",
      "Hand placed on the abdomen",
      "قرار دادن دست روی شکم",
      ["hand_region_contact"], ["physical_discomfort", "hunger_thirst", "self_support", "clothing", "posture_habit"],
      detector="event", gates=("pose", "hands"), threshold=1, window_s=5, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("hand_cover_face", "hands_arms",
      "One or both hands covering a large part of the face",
      "پوشاندن بخش بزرگی از صورت با یک یا دو دست",
      ["hand_covering_face_score"], ["fatigue", "thinking", "privacy_need", "emotional_response", "humor", "dry_eyes"],
      detector="sustained", gates=("face", "hands"), threshold=0.4, min_duration_s=2, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1],
      note_en="Also suspends facial scoring (quality gate).", note_fa="امتیازدهی چهره را هم متوقف می‌کند (دروازه کیفیت)."),
    S("head_in_hands", "hands_arms",
      "Head resting in both hands",
      "سر در میان دو دست",
      ["head_support_score", "hand_covering_face_score"], ["fatigue", "physical_discomfort", "thinking", "self_support", "emotional_response"],
      detector="sustained", gates=("face", "hands"), threshold=0.6, min_duration_s=3, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("chin_rest_on_hand", "hands_arms",
      "Chin or cheek resting on hand",
      "تکیه دادن چانه یا گونه روی دست",
      ["head_support_score"], ["fatigue", "self_support", "thinking", "boredom", "posture_habit"],
      detector="sustained", gates=("face", "hands"), threshold=0.5, min_duration_s=8, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("self_touch_rate_change", "hands_arms",
      "Overall self-touch frequency changed from baseline",
      "تعداد کل خودلمسی نسبت به خط پایه تغییر کرده است",
      ["hand_contact_event"], ["habit", "itching", "temperature", "interaction_change", "topic_related", "fatigue"],
      tier="change", detector="rate_change", gates=("hands",), rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("self_touch_duration_change", "hands_arms",
      "Average duration of self-touch episodes changed",
      "میانگین مدت دوره‌های خودلمسی تغییر کرده است",
      ["hand_contact_duration"], ["self_support", "fatigue", "habit", "thinking"],
      tier="change", gates=("hands",), window_s=120, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("wrist_rubbing", "hands_arms",
      "Rubbing wrist or hand with the other hand",
      "مالیدن مچ یا دست با دست دیگر",
      ["hand_region_contact", "hands_clasped_score", "finger_motion_energy"], ["physical_discomfort", "temperature", "self_soothing", "habit"],
      detector="sustained", gates=("hands",), threshold=0.5, min_duration_s=3, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("hands_clasped_sustained", "hands_arms",
      "Hands clasped together for a sustained period",
      "قلاب شدن دست‌ها برای مدتی طولانی",
      ["hands_clasped_score"], ["posture_habit", "temperature", "self_support", "politeness"],
      detector="sustained", gates=("hands",), threshold=0.7, min_duration_s=15, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("hands_wringing", "hands_arms",
      "Repetitive hand-over-hand movement (wringing)",
      "حرکت تکراری دست روی دست (به هم پیچاندن)",
      ["hands_clasped_score", "finger_motion_energy", "hand_oscillation_hz"], ["temperature", "self_soothing", "habit", "restlessness", "physical_discomfort"],
      detector="periodicity", gates=("hands",), band=(0.5, 3.0), min_duration_s=4, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("hands_hidden_sustained", "hands_arms",
      "Hands out of frame / below desk for a sustained period",
      "دست‌ها برای مدتی طولانی خارج از کادر یا زیر میز هستند",
      ["hands_visible"], ["camera_framing", "posture_habit", "object_manipulation", "temperature"],
      tier="quality", detector="sustained", gates=("pose",), threshold=0, min_duration_s=60, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1],
      note_en="Quality flag: hand-based signals are unavailable.", note_fa="پرچم کیفیت: سیگنال‌های دست در دسترس نیستند."),
    S("hand_fidgeting", "hands_arms",
      "Repeated small hand/finger movements without an object",
      "حرکات ریز و تکراری دست/انگشت بدون شیء",
      ["finger_motion_energy", "hand_oscillation_hz"], ["habit", "restlessness", "cognitive_effort", "temperature"],
      detector="sustained", gates=("hands",), threshold=1.5, min_duration_s=5, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1],
      note_en="Only surface if hands are reliably visible.", note_fa="فقط در صورت دیده شدن قابل اعتماد دست‌ها نمایش داده شود."),
    S("hand_fidget_rate_change", "hands_arms",
      "Fidgeting episodes more/less frequent than baseline",
      "دوره‌های وول خوردن دست بیشتر/کمتر از خط پایه شده است",
      ["finger_motion_energy"], ["habit", "restlessness", "cognitive_effort", "topic_related", "fatigue"],
      tier="change", detector="rate_change", gates=("hands",), rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("finger_tapping", "hands_arms",
      "Rhythmic finger tapping",
      "ضربه زدن ریتمیک با انگشت",
      ["finger_tap_event", "hand_oscillation_hz"], ["habit", "music", "restlessness", "thinking"],
      detector="periodicity", gates=("hands",), band=(1.0, 6.0), min_duration_s=3, rationale_en=R_MOTOR[0], rationale_fa=R_MOTOR[1]),
    S("object_manipulation", "hands_arms",
      "Manipulating an object (pen, phone, jewellery)",
      "بازی با شیء (خودکار، گوشی، زیورآلات)",
      ["hand_object_score", "finger_motion_energy"], ["habit", "object_manipulation", "restlessness", "distraction"],
      detector="sustained", gates=("hands",), threshold=0.6, min_duration_s=5, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("nail_biting_like", "hands_arms",
      "Fingertips at mouth with small repetitive motion",
      "نوک انگشتان در دهان با حرکت ریز تکراری",
      ["hand_region_contact", "finger_motion_energy"], ["habit", "self_soothing", "thinking", "hunger_thirst"],
      detector="sustained", gates=("face", "hands"), threshold=1, min_duration_s=3, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1]),
    S("skin_picking_like", "hands_arms",
      "Repeated contact at the same small skin location",
      "تماس مکرر با یک نقطه کوچک پوست",
      ["hand_region_contact", "hand_contact_event", "finger_motion_energy"], ["itching", "illness", "habit", "self_soothing"],
      detector="rate_change", gates=("hands",), threshold=2.5, rationale_en=R_ADAPT[0], rationale_fa=R_ADAPT[1],
      note_en="Observation only; the clinician may ask about skin/dermatological factors.", note_fa="فقط مشاهده؛ درمانگر می‌تواند درباره عوامل پوستی بپرسد."),
    S("hand_tremor_like", "hands_arms",
      "High-frequency oscillation of hand landmarks at rest",
      "نوسان سریع نقاط دست در حالت استراحت",
      ["hand_oscillation_hz", "hand_oscillation_amplitude"], ["caffeine", "temperature", "medication", "neurological", "technical_issue", "emotional_response"],
      tier="medical", detector="periodicity", gates=("hands",), band=(3.0, 12.0), min_duration_s=3, rationale_en=R_MOTOR[0], rationale_fa=R_MOTOR[1],
      note_en="Medical flag: consider medication, caffeine, physiological or neurological factors; not a psychological label.",
      note_fa="پرچم پزشکی: دارو، کافئین، عوامل فیزیولوژیک یا عصبی را در نظر بگیرید؛ برچسب روان‌شناختی نیست."),
    S("hand_stillness_increase", "hands_arms",
      "Hand movement markedly reduced from baseline",
      "حرکت دست‌ها نسبت به خط پایه به‌طور محسوس کاهش یافته است",
      ["hand_velocity_left", "hand_velocity_right", "finger_motion_energy"], ["thinking", "fatigue", "posture_habit", "low_energy", "camera_framing"],
      tier="change", gates=("hands",), direction="down", threshold=-2.0, window_s=60, rationale_en=R_GEST[0], rationale_fa=R_GEST[1]),

    # ------------------------------------------------------------------ gestures
    S("gesture_rate_increase", "gestures",
      "Co-speech gesture rate increased from baseline",
      "نرخ ژست‌های هم‌زمان با گفتار نسبت به خط پایه افزایش یافته است",
      ["gesture_event"], ["topic", "speech_emphasis", "communication_style", "activation", "engagement"],
      tier="change", detector="rate_change", gates=("hands",), speaker_state="patient_speaking", rationale_en=R_GEST[0], rationale_fa=R_GEST[1]),
    S("gesture_rate_decrease", "gestures",
      "Co-speech gesture rate decreased from baseline",
      "نرخ ژست‌های هم‌زمان با گفتار نسبت به خط پایه کاهش یافته است",
      ["gesture_event"], ["topic", "fatigue", "camera_framing", "low_energy", "thinking"],
      tier="change", detector="rate_change", gates=("hands",), threshold=0.5, direction="down", speaker_state="patient_speaking", rationale_en=R_GEST[0], rationale_fa=R_GEST[1]),
    S("gesture_amplitude_change", "gestures",
      "Spatial extent of gestures changed from baseline",
      "دامنه فضایی ژست‌ها نسبت به خط پایه تغییر کرده است",
      ["gesture_amplitude"], ["speech_emphasis", "camera_framing", "activation", "fatigue"],
      tier="change", gates=("hands",), speaker_state="patient_speaking", window_s=120, rationale_en=R_GEST[0], rationale_fa=R_GEST[1]),
    S("gesture_speed_change", "gestures",
      "Gesture speed changed from baseline",
      "سرعت ژست‌ها نسبت به خط پایه تغییر کرده است",
      ["gesture_speed"], ["speech_emphasis", "activation", "fatigue", "urgency"],
      tier="change", gates=("hands",), speaker_state="patient_speaking", window_s=120, rationale_en=R_GEST[0], rationale_fa=R_GEST[1]),
    S("gesture_speech_desync", "gestures",
      "Gestures less aligned with speech than baseline",
      "هم‌زمانی ژست با گفتار نسبت به خط پایه کمتر شده است",
      ["gesture_speech_alignment"], ["object_manipulation", "restlessness", "network_latency", "habit"],
      tier="change", gates=("hands",), direction="down", window_s=180, rationale_en=R_GEST[0], rationale_fa=R_GEST[1]),
    S("open_palm_gesture_rate_change", "gestures",
      "Rate of open-palm gestures changed",
      "نرخ ژست‌های با کف دست باز تغییر کرده است",
      ["palm_orientation", "gesture_event"], ["communication_style", "speech_emphasis", "cultural_norm"],
      tier="change", detector="rate_change", gates=("hands",), rationale_en=R_GEST[0], rationale_fa=R_GEST[1]),
    S("pointing_gesture_event", "gestures",
      "Pointing gesture",
      "ژست اشاره",
      ["pointing_score"], ["speech_emphasis", "communication_style", "other_person", "screen_use"],
      detector="event", gates=("hands",), threshold=0.7, window_s=3, rationale_en=R_GEST[0], rationale_fa=R_GEST[1]),
    S("gesture_burst", "gestures",
      "Dense burst of gestures in a short interval",
      "رگبار ژست‌ها در فاصله زمانی کوتاه",
      ["gesture_event"], ["speech_emphasis", "activation", "topic", "urgency"],
      detector="event", gates=("hands",), threshold=5, window_s=10, rationale_en=R_GEST[0], rationale_fa=R_GEST[1]),

    # ------------------------------------------------------------------ lower body
    S("leg_bounce_like", "lower_body",
      "Repeated rhythmic lower-limb motion",
      "حرکت ریتمیک و تکراری پا",
      ["knee_oscillation_hz"], ["habit", "music", "restlessness", "temperature", "caffeine"],
      detector="periodicity", gates=("lower_body",), band=(1.0, 6.0), min_duration_s=4, rationale_en=R_MOTOR[0], rationale_fa=R_MOTOR[1],
      note_en="Only when lower body is clearly visible.", note_fa="فقط وقتی پایین‌تنه به‌وضوح دیده می‌شود."),
    S("foot_tapping_like", "lower_body",
      "Repeated rhythmic foot motion",
      "ضربه ریتمیک پا",
      ["ankle_oscillation_hz"], ["habit", "music", "restlessness"],
      detector="periodicity", gates=("lower_body",), band=(1.0, 6.0), min_duration_s=4, rationale_en=R_MOTOR[0], rationale_fa=R_MOTOR[1]),
    S("leg_bounce_rate_change", "lower_body",
      "Leg-bounce episodes more/less frequent than baseline",
      "دوره‌های تکان دادن پا بیشتر/کمتر از خط پایه شده است",
      ["knee_oscillation_hz"], ["restlessness", "habit", "topic_related", "caffeine"],
      tier="change", detector="rate_change", gates=("lower_body",), rationale_en=R_MOTOR[0], rationale_fa=R_MOTOR[1]),
    S("leg_cross_change_event", "lower_body",
      "Leg crossing state changed",
      "وضعیت روی هم انداختن پاها تغییر کرد",
      ["leg_cross_state"], ["chair", "physical_discomfort", "posture_habit", "stretching"],
      detector="event", gates=("lower_body",), threshold=1, window_s=5, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("leg_cross_change_rate", "lower_body",
      "Frequency of leg re-crossing changed from baseline",
      "تعداد تغییر حالت پاها نسبت به خط پایه تغییر کرده است",
      ["leg_cross_state"], ["chair", "physical_discomfort", "restlessness"],
      tier="change", detector="rate_change", gates=("lower_body",), rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("frequent_seat_shift", "lower_body",
      "Frequent whole-body repositioning on the seat",
      "جابه‌جایی مکرر کل بدن روی صندلی",
      ["hip_shift_event"], ["chair", "physical_discomfort", "restlessness", "temperature"],
      tier="change", detector="rate_change", gates=("pose",), rationale_en=R_POST[0], rationale_fa=R_POST[1],
      note_en="Ask/consider physical comfort.", note_fa="راحتی جسمی را بپرسید یا در نظر بگیرید."),
    S("standing_up_event", "lower_body",
      "Patient stood up / left the seat",
      "بیمار از صندلی بلند شد",
      ["standing_event", "body_scale"], ["interruption", "device_handling", "physical_discomfort", "privacy_need", "restlessness"],
      tier="quality", detector="event", gates=("pose",), threshold=1, window_s=5, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("leg_stillness_increase", "lower_body",
      "Lower-body motion reduced from baseline",
      "حرکت پایین‌تنه نسبت به خط پایه کاهش یافته است",
      ["knee_oscillation_hz", "hip_shift_event"], ["chair", "engagement", "fatigue", "low_energy"],
      tier="change", gates=("lower_body",), direction="down", window_s=120, rationale_en=R_MOTOR[0], rationale_fa=R_MOTOR[1]),

    # ------------------------------------------------------------------ whole-body motion
    S("motion_energy_increase", "whole_body_motion",
      "Whole-body motion energy increased from baseline",
      "انرژی حرکتی کل بدن نسبت به خط پایه افزایش یافته است",
      ["motion_energy_total"], ["restlessness", "speech_emphasis", "activation", "chair", "device_handling"],
      tier="change", gates=("pose",), direction="up", window_s=60, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("motion_energy_decrease", "whole_body_motion",
      "Whole-body motion energy decreased from baseline",
      "انرژی حرکتی کل بدن نسبت به خط پایه کاهش یافته است",
      ["motion_energy_total"], ["thinking", "fatigue", "engagement", "low_energy", "technical_issue"],
      tier="change", gates=("pose",), direction="down", threshold=-2.0, window_s=60, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("movement_speed_reduction", "whole_body_motion",
      "Movements slower than baseline (peak velocities reduced)",
      "حرکات کندتر از خط پایه (کاهش اوج سرعت)",
      ["hand_velocity_left", "hand_velocity_right", "head_angular_velocity", "gesture_speed"], ["fatigue", "medication", "low_energy", "illness", "thinking"],
      tier="change", gates=("pose",), direction="down", threshold=-2.0, window_s=180, rationale_en=R_POST[0], rationale_fa=R_POST[1],
      note_en="Describe as slower movement; never use 'psychomotor retardation' as an automatic label.",
      note_fa="به‌عنوان کند شدن حرکت توصیف شود؛ هرگز برچسب خودکار «کندی روانی‌حرکتی» زده نشود."),
    S("movement_speed_increase", "whole_body_motion",
      "Movements faster than baseline",
      "حرکات سریع‌تر از خط پایه",
      ["hand_velocity_left", "hand_velocity_right", "head_angular_velocity"], ["activation", "speech_emphasis", "urgency", "caffeine", "restlessness"],
      tier="change", gates=("pose",), direction="up", window_s=180, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("sudden_movement_event", "whole_body_motion",
      "Sudden high-acceleration body movement (startle-like)",
      "حرکت ناگهانی و پرشتاب بدن (شبیه یکه خوردن)",
      ["sudden_motion_event"], ["noise", "interruption", "surprise", "device_handling", "physical_discomfort"],
      detector="event", gates=("pose",), threshold=1, window_s=3, rationale_en=R_POST[0], rationale_fa=R_POST[1]),
    S("motion_freezing_episode", "whole_body_motion",
      "Abrupt transition from movement to near-complete stillness",
      "گذار ناگهانی از حرکت به سکون تقریباً کامل",
      ["motion_energy_total", "stillness_duration"], ["thinking", "surprise", "technical_issue", "engagement", "emotional_response"],
      detector="event", gates=("pose",), threshold=1, window_s=10, rationale_en=R_POST[0], rationale_fa=R_POST[1],
      note_en="Check frame counter to exclude frozen video.", note_fa="برای رد کردن فریز ویدئو، شمارنده فریم را بررسی کنید."),
    S("rhythmic_whole_body_motion", "whole_body_motion",
      "Rhythmic repetitive whole-body movement",
      "حرکت ریتمیک و تکراری کل بدن",
      ["motion_energy_total", "torso_oscillation_hz"], ["music", "self_soothing", "habit", "chair", "neurological"],
      detector="periodicity", gates=("pose",), band=(0.2, 3.0), min_duration_s=10, rationale_en=R_MOTOR[0], rationale_fa=R_MOTOR[1]),
    S("repetitive_motor_pattern", "whole_body_motion",
      "Same brief movement repeated many times (tic-like)",
      "تکرار مکرر یک حرکت کوتاه (شبیه تیک)",
      ["sudden_motion_event", "head_angular_velocity", "au_activity_total"], ["habit", "neurological", "medication", "restlessness"],
      tier="medical", detector="rate_change", gates=("face", "pose"), threshold=3.0, rationale_en=R_MOTOR[0], rationale_fa=R_MOTOR[1],
      note_en="Medical flag for clinician review; never a diagnosis.", note_fa="پرچم پزشکی برای بررسی درمانگر؛ هرگز تشخیص نیست."),
    S("movement_asymmetry_sustained", "whole_body_motion",
      "One side of the body moves markedly less than the other",
      "یک سمت بدن به‌طور محسوس کمتر از سمت دیگر حرکت می‌کند",
      ["motion_symmetry"], ["camera_placement", "posture_habit", "physical_discomfort", "neurological", "object_manipulation"],
      tier="medical", detector="sustained", gates=("pose",), threshold=0.35, min_duration_s=120, rationale_en=R_MOTOR[0], rationale_fa=R_MOTOR[1]),
    S("activity_level_trend", "whole_body_motion",
      "Overall activity level trends up/down across the session",
      "سطح کلی فعالیت در طول جلسه روند صعودی/نزولی دارد",
      ["motion_energy_total", "gesture_event", "pose_change_event"], ["session_phase", "fatigue", "rapport", "topic", "engagement"],
      tier="change", detector="trend", gates=("pose",), rationale_en=R_POST[0], rationale_fa=R_POST[1]),
]
