"""Dyadic synchrony, multimodal clusters, environment/technical quality and operational signals."""

from signal_helpers import S

R_DYAD = ("Interpersonal synchrony (mirroring, nodding in time, prosodic convergence) is studied as a "
          "correlate of rapport. It requires the clinician's own features and is optional; it is never a "
          "measure of the patient alone.",
          "هم‌زمانی بین‌فردی (آینه‌ای شدن، سر تکان دادن هم‌زمان، همگرایی عروضی) به‌عنوان هم‌بسته رابطه درمانی مطالعه می‌شود. "
          "نیازمند ویژگی‌های خود درمانگر است و اختیاری است؛ هرگز سنجه‌ای از بیمار به‌تنهایی نیست.")
R_CLUS = ("A cluster means several independent observable channels changed near the same moment. That is "
          "stronger evidence that *something* changed than any single signal, but it still says nothing "
          "about what or why. The clinician is asked to review the segment.",
          "خوشه یعنی چند کانال مستقل قابل مشاهده در نزدیکی یک لحظه تغییر کرده‌اند. این شاهد قوی‌تری از هر سیگنال منفرد است که «چیزی» تغییر کرده، "
          "اما همچنان درباره چه و چرا چیزی نمی‌گوید. از درمانگر خواسته می‌شود بخش را بازبینی کند.")
R_QUAL = ("Quality flags explain why other signals are suppressed and prevent artefacts from being shown as "
          "behaviour.",
          "پرچم‌های کیفیت توضیح می‌دهند چرا سیگنال‌های دیگر متوقف شده‌اند و مانع نمایش مصنوعات فنی به‌عنوان رفتار می‌شوند.")

SIGNALS = [
    # ------------------------------------------------------------------ dyadic synchrony
    S("posture_mirroring_change", "interaction_synchrony",
      "Postural mirroring with clinician changed from baseline",
      "آینه‌ای شدن وضعیت بدن با درمانگر نسبت به خط پایه تغییر کرده است",
      ["posture_mirroring_score"], ["rapport", "coincidence", "chair", "interaction_change"],
      tier="change", gates=("dyad",), window_s=300, rationale_en=R_DYAD[0], rationale_fa=R_DYAD[1]),
    S("nod_synchrony_change", "interaction_synchrony",
      "Nodding in time with clinician speech changed from baseline",
      "هم‌زمانی سر تکان دادن با گفتار درمانگر تغییر کرده است",
      ["nod_sync_score"], ["engagement", "conversational_feedback", "network_latency", "cultural_norm"],
      tier="change", gates=("dyad",), window_s=300, rationale_en=R_DYAD[0], rationale_fa=R_DYAD[1]),
    S("prosodic_convergence_change", "interaction_synchrony",
      "Pitch/rate convergence with clinician changed",
      "همگرایی زیر و بمی/نرخ گفتار با درمانگر تغییر کرده است",
      ["prosodic_convergence"], ["rapport", "language", "interaction_change", "fatigue"],
      tier="change", gates=("audio",), window_s=600, rationale_en=R_DYAD[0], rationale_fa=R_DYAD[1]),
    S("smile_reciprocity_change", "interaction_synchrony",
      "Reciprocal smiling changed from baseline",
      "لبخند متقابل نسبت به خط پایه تغییر کرده است",
      ["smile_reciprocity"], ["rapport", "humor", "politeness", "cultural_norm", "lighting"],
      tier="change", gates=("dyad",), window_s=300, rationale_en=R_DYAD[0], rationale_fa=R_DYAD[1]),

    # ------------------------------------------------------------------ multimodal clusters
    S("topic_linked_behavior_change", "multimodal_clusters",
      "Several observable signals changed within a short window after a question or topic shift",
      "چند سیگنال قابل مشاهده در بازه کوتاهی پس از سؤال یا تغییر موضوع تغییر کرده‌اند",
      ["question_event", "topic_segment_id"], ["topic_related", "coincidence", "fatigue", "session_phase"],
      tier="cluster", detector="cluster", gates=("none",), threshold=3, window_s=20,
      members=["*"], rationale_en=R_CLUS[0], rationale_fa=R_CLUS[1],
      note_en="Surface as correlation, never causation. Link to transcript segment.", note_fa="به‌عنوان هم‌زمانی نمایش داده شود، نه علیت. به بخش متن پیوند بخورد."),
    S("response_cluster_change", "multimodal_clusters",
      "Cluster of behavioral changes around a specific patient response",
      "خوشه‌ای از تغییرات رفتاری پیرامون یک پاسخ مشخص بیمار",
      ["question_event", "speaker"], ["topic_related", "question_type", "coincidence", "thinking"],
      tier="cluster", detector="cluster", gates=("none",), threshold=3, window_s=15,
      members=["response_latency_increase", "speech_rate_decrease", "pause_duration_increase", "volume_decrease",
               "gaze_away_sustained", "head_down_sustained", "hand_to_face_event", "lip_press_sustained",
               "posture_change_rate_increase", "expressiveness_decrease"],
      rationale_en=R_CLUS[0], rationale_fa=R_CLUS[1],
      note_en="Present as: 'N observable signals changed from baseline around this response. Consider reviewing this segment.'",
      note_fa="نمایش: «N سیگنال قابل مشاهده پیرامون این پاسخ نسبت به خط پایه تغییر کردند. بازبینی این بخش را در نظر بگیرید.»"),
    S("activation_cluster", "multimodal_clusters",
      "Co-occurring increases in motion, speech rate, loudness and pitch variability",
      "افزایش هم‌زمان حرکت، نرخ گفتار، بلندی و تغییرپذیری زیر و بمی",
      ["motion_energy_total", "speech_rate_wpm", "loudness_rms_db", "f0_std"], ["activation", "speech_emphasis", "topic", "caffeine", "humor"],
      tier="cluster", detector="cluster", gates=("none",), threshold=3, window_s=30,
      members=["motion_energy_increase", "speech_rate_increase", "volume_increase", "pitch_variability_increase",
               "gesture_rate_increase", "head_motion_increase", "pause_rate_decrease"],
      rationale_en=R_CLUS[0], rationale_fa=R_CLUS[1]),
    S("reduced_activity_cluster", "multimodal_clusters",
      "Co-occurring decreases in motion, speech rate, loudness, gesture and facial activity",
      "کاهش هم‌زمان حرکت، نرخ گفتار، بلندی، ژست و فعالیت چهره",
      ["motion_energy_total", "speech_rate_wpm", "loudness_rms_db", "au_activity_total"], ["fatigue", "low_energy", "thinking", "medication", "session_phase", "emotional_response"],
      tier="cluster", detector="cluster", gates=("none",), threshold=3, window_s=60,
      members=["motion_energy_decrease", "speech_rate_decrease", "volume_decrease", "gesture_rate_decrease",
               "expressiveness_decrease", "pitch_variability_decrease", "utterance_length_decrease", "movement_speed_reduction"],
      rationale_en=R_CLUS[0], rationale_fa=R_CLUS[1],
      note_en="Never output 'depressed' or 'withdrawn'; output the member list and values.", note_fa="هرگز «افسرده» یا «منزوی» خروجی داده نشود؛ فهرست اعضا و مقادیر نمایش داده شود."),
    S("tension_like_cluster", "multimodal_clusters",
      "Co-occurring lip press, shoulder elevation, hand-to-neck/face and reduced blink",
      "هم‌زمانی فشردن لب، بالا بودن شانه، دست به گردن/صورت و کاهش پلک",
      ["lip_thickness", "shoulder_neck_distance", "hand_region_contact", "blink_event"], ["physical_discomfort", "temperature", "cognitive_effort", "chair", "affective_expression"],
      tier="cluster", detector="cluster", gates=("none",), threshold=3, window_s=30,
      members=["lip_press_sustained", "shoulder_elevation_sustained", "hand_to_neck", "hand_to_face_event", "blink_rate_decrease",
               "jaw_clench_like_sustained", "hands_clasped_sustained", "brow_lower_sustained"],
      rationale_en=R_CLUS[0], rationale_fa=R_CLUS[1],
      note_en="Named after body geometry, not emotion. Do not output 'anxious'.", note_fa="بر اساس هندسه بدن نام‌گذاری شده، نه هیجان. «مضطرب» خروجی داده نشود."),
    S("fatigue_like_cluster", "multimodal_clusters",
      "Co-occurring long blinks, partial eye closure, slump, yawns and slowed speech",
      "هم‌زمانی پلک‌های طولانی، نیمه‌بسته بودن چشم، خمیدگی، خمیازه و کند شدن گفتار",
      ["blink_duration", "eye_aperture_mean", "torso_angle", "speech_rate_wpm"], ["fatigue", "session_phase", "medication", "illness", "boredom"],
      tier="cluster", detector="cluster", gates=("none",), threshold=3, window_s=120,
      members=["blink_duration_long", "partial_eye_closure_sustained", "slumped_posture_sustained", "yawn_like_event", "yawn_audible_event",
               "speech_rate_decrease", "chin_rest_on_hand", "eye_closure_long", "movement_speed_reduction"],
      rationale_en=R_CLUS[0], rationale_fa=R_CLUS[1],
      note_en="Suggest the clinician ask about sleep/rest only if clinically appropriate.", note_fa="فقط در صورت مناسب بودن بالینی، پرسش درباره خواب/استراحت پیشنهاد شود."),
    S("distraction_like_cluster", "multimodal_clusters",
      "Co-occurring gaze away, head turn, longer response latency and backchannel drop",
      "هم‌زمانی نگاه به بیرون، چرخش سر، افزایش تأخیر پاسخ و کاهش بازخورد شنونده",
      ["gaze_on_screen", "head_yaw", "response_latency_ms", "backchannel_event"], ["distraction", "other_person", "device_handling", "noise", "thinking"],
      tier="cluster", detector="cluster", gates=("none",), threshold=3, window_s=45,
      members=["gaze_away_sustained", "head_turn_away_sustained", "response_latency_increase", "backchannel_rate_change",
               "object_manipulation", "minimal_response_to_open_question", "gaze_scanning_increase"],
      rationale_en=R_CLUS[0], rationale_fa=R_CLUS[1]),
    S("content_behavior_divergence", "multimodal_clusters",
      "Verbal content and observable behaviour changed in different directions around the same moment",
      "محتوای کلامی و رفتار قابل مشاهده پیرامون یک لحظه در جهت‌های متفاوت تغییر کرده‌اند",
      ["negative_lexicon_ratio", "positive_lexicon_ratio", "au_activity_total", "loudness_rms_db", "response_latency_ms"],
      ["cultural_norm", "politeness", "self_soothing", "asr_error", "coincidence", "figure_of_speech"],
      tier="cluster", detector="cluster", gates=("asr",), threshold=2, window_s=15,
      members=["minimal_response_to_open_question", "response_latency_increase", "expressiveness_decrease", "volume_decrease",
               "laughter_speech_content_mismatch", "hand_to_face_event", "gaze_away_sustained", "speech_rate_decrease"],
      rationale_en=R_CLUS[0], rationale_fa=R_CLUS[1],
      note_en="Example: answer 'nothing, I don't care' while 4 signals changed. Output only: 'A cluster of behavioural changes occurred around this response; consider reviewing.' Never 'lying' or 'masking'.",
      note_fa="مثال: پاسخ «هیچی، برام مهم نیست» در حالی که ۴ سیگنال تغییر کرده‌اند. فقط خروجی: «خوشه‌ای از تغییرات رفتاری پیرامون این پاسخ رخ داد؛ بازبینی را در نظر بگیرید.» هرگز «دروغ» یا «پنهان‌کاری»."),
    S("engagement_shift_cluster", "multimodal_clusters",
      "Co-occurring changes in lean, gaze-to-camera, nodding and backchannels",
      "تغییرات هم‌زمان در تمایل تنه، نگاه به دوربین، سر تکان دادن و بازخورد شنونده",
      ["torso_angle", "gaze_on_camera", "head_pitch", "backchannel_event"], ["engagement", "interaction_change", "fatigue", "topic", "chair"],
      tier="cluster", detector="cluster", gates=("none",), threshold=3, window_s=60,
      members=["lean_forward", "lean_back", "gaze_to_camera_ratio_change", "head_nod_rate_change", "backchannel_rate_change",
               "facial_activity_during_listening_change"],
      rationale_en=R_CLUS[0], rationale_fa=R_CLUS[1]),
    S("session_phase_drift", "multimodal_clusters",
      "Gradual drift of multiple baselines across the session (start vs end)",
      "رانش تدریجی چند خط پایه در طول جلسه (شروع در برابر پایان)",
      ["motion_energy_total", "speech_rate_wpm", "au_activity_total", "blink_event"], ["session_phase", "fatigue", "rapport", "topic"],
      tier="change", detector="trend", gates=("none",), threshold=0.3, window_s=900,
      rationale_en=R_CLUS[0], rationale_fa=R_CLUS[1],
      note_en="Shown in the end-of-session report, not live.", note_fa="در گزارش پایان جلسه نمایش داده شود، نه به‌صورت زنده."),

    # ------------------------------------------------------------------ environment / technical quality
    S("camera_exit", "environment_technical",
      "Face/body left the frame",
      "چهره/بدن از کادر خارج شد",
      ["persons_detected", "face_in_frame_ratio"], ["device_handling", "privacy_need", "interruption", "technical_issue"],
      tier="quality", detector="quality", gates=("none",), threshold=0, min_duration_s=2, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1],
      note_en="Operational event, not psychological inference.", note_fa="رویداد عملیاتی، نه استنباط روان‌شناختی."),
    S("face_partially_out_of_frame", "environment_technical",
      "Face partially outside the frame",
      "چهره تا حدی خارج از کادر است",
      ["face_in_frame_ratio"], ["camera_placement", "posture_habit", "device_handling"],
      tier="quality", detector="quality", gates=("none",), threshold=0.85, direction="down", min_duration_s=5, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("face_too_small", "environment_technical",
      "Face too small in frame for reliable facial analysis",
      "چهره برای تحلیل قابل اعتماد بیش از حد کوچک است",
      ["face_size_px"], ["camera_placement", "chair"],
      tier="quality", detector="quality", gates=("none",), threshold=120, direction="down", min_duration_s=10, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("low_light", "environment_technical",
      "Insufficient illumination on the face",
      "نور ناکافی روی چهره",
      ["illumination"], ["lighting"],
      tier="quality", detector="quality", gates=("none",), threshold=0.3, direction="down", min_duration_s=10, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("backlight_glare", "environment_technical",
      "Strong backlight / glare on face or glasses",
      "نور پس‌زمینه شدید یا انعکاس روی چهره یا عینک",
      ["illumination", "glasses_detected"], ["lighting", "glasses"],
      tier="quality", detector="quality", gates=("none",), threshold=0.9, direction="up", min_duration_s=10, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("occlusion_by_hand", "environment_technical",
      "Face occluded by hands (facial signals suspended)",
      "چهره با دست پوشیده شده (سیگنال‌های چهره متوقف شدند)",
      ["hand_covering_face_score"], ["habit", "self_support", "privacy_need"],
      tier="quality", detector="quality", gates=("none",), threshold=0.4, direction="up", min_duration_s=2, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("mask_or_object_occlusion", "environment_technical",
      "Face covering / object occluding mouth region",
      "پوشش صورت یا شیئی که ناحیه دهان را می‌پوشاند",
      ["mask_detected"], ["clothing", "illness", "privacy_need"],
      tier="quality", detector="quality", gates=("none",), threshold=1, min_duration_s=5, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("multiple_faces_detected", "environment_technical",
      "More than one face in the frame",
      "بیش از یک چهره در کادر",
      ["faces_detected", "persons_detected"], ["other_person", "privacy_need", "interruption"],
      tier="quality", detector="quality", gates=("none",), threshold=2, direction="up", min_duration_s=2, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1],
      note_en="Analysis pauses; the clinician is informed. Privacy relevant.", note_fa="تحلیل متوقف می‌شود؛ درمانگر مطلع می‌شود. مرتبط با حریم خصوصی."),
    S("camera_angle_extreme", "environment_technical",
      "Camera angle too steep for reliable pose/gaze estimation",
      "زاویه دوربین برای تخمین قابل اعتماد وضعیت/نگاه بیش از حد تند است",
      ["head_pitch", "head_yaw", "pose_quality"], ["camera_placement", "device_handling"],
      tier="quality", detector="quality", gates=("none",), threshold=35, direction="up", min_duration_s=20, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("motion_blur_high", "environment_technical",
      "Motion blur high (fast movement or low frame rate)",
      "تاری حرکتی زیاد (حرکت سریع یا نرخ فریم پایین)",
      ["motion_blur", "fps"], ["technical_issue", "device_handling"],
      tier="quality", detector="quality", gates=("none",), threshold=0.6, direction="up", min_duration_s=3, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("frame_rate_low", "environment_technical",
      "Effective analysis frame rate too low for periodicity signals",
      "نرخ فریم مؤثر تحلیل برای سیگنال‌های ریتمیک بیش از حد پایین است",
      ["fps"], ["technical_issue"],
      tier="quality", detector="quality", gates=("none",), threshold=12, direction="down", min_duration_s=10, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("video_frozen", "environment_technical",
      "Video frames identical for several seconds (frozen stream)",
      "فریم‌های ویدئو برای چند ثانیه یکسان هستند (جریان فریز شده)",
      ["fps", "motion_energy_total", "face_landmark_motion_energy"], ["technical_issue", "network_latency"],
      tier="quality", detector="quality", gates=("none",), threshold=0, min_duration_s=3, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1],
      note_en="Suppresses stillness/freezing signals.", note_fa="سیگنال‌های سکون را سرکوب می‌کند."),
    S("audio_snr_low", "environment_technical",
      "Audio signal-to-noise ratio too low for prosody",
      "نسبت سیگنال به نویز صدا برای تحلیل عروض بیش از حد پایین است",
      ["audio_snr_db"], ["noise", "microphone", "technical_issue"],
      tier="quality", detector="quality", gates=("none",), threshold=15, direction="down", min_duration_s=5, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("audio_clipping", "environment_technical",
      "Audio clipping (mic gain too high)",
      "اشباع صدا (بهره میکروفون بیش از حد بالا)",
      ["audio_clipping_ratio"], ["microphone", "technical_issue"],
      tier="quality", detector="quality", gates=("none",), threshold=0.02, direction="up", min_duration_s=3, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("echo_or_feedback", "environment_technical",
      "Acoustic echo / feedback detected",
      "اکو یا فیدبک صوتی شناسایی شد",
      ["audio_quality", "spectral_flux"], ["technical_issue", "microphone"],
      tier="quality", detector="quality", gates=("none",), threshold=0.5, direction="down", min_duration_s=3, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("background_noise_event", "environment_technical",
      "Transient background sound (door, phone, traffic)",
      "صدای گذرای پس‌زمینه (در، تلفن، ترافیک)",
      ["background_noise_event"], ["noise", "interruption"],
      tier="quality", detector="event", gates=("none",), threshold=1, window_s=5, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1],
      note_en="Used to explain startle-like or head-turn events.", note_fa="برای توضیح رویدادهای یکه خوردن یا چرخش سر استفاده می‌شود."),
    S("background_voice_detected", "environment_technical",
      "Second voice detected in the patient's audio",
      "صدای فرد دوم در صدای بیمار شناسایی شد",
      ["background_voice_event"], ["other_person", "privacy_need", "interruption"],
      tier="quality", detector="event", gates=("none",), threshold=1, window_s=5, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1],
      note_en="Privacy relevant; clinician informed; analysis may pause.", note_fa="مرتبط با حریم خصوصی؛ درمانگر مطلع می‌شود؛ تحلیل ممکن است متوقف شود."),
    S("network_latency_high", "environment_technical",
      "Network round-trip time high; timing signals unreliable",
      "زمان رفت و برگشت شبکه بالا؛ سیگنال‌های زمانی غیرقابل اعتماد",
      ["network_rtt_ms"], ["network_latency", "technical_issue"],
      tier="quality", detector="quality", gates=("none",), threshold=400, direction="up", min_duration_s=5, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("packet_loss_high", "environment_technical",
      "Packet loss high; audio/video artefacts likely",
      "افت بسته بالا؛ احتمال مصنوعات صوتی/تصویری",
      ["packet_loss"], ["network_latency", "technical_issue"],
      tier="quality", detector="quality", gates=("none",), threshold=0.05, direction="up", min_duration_s=5, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("camera_moved", "environment_technical",
      "Camera or device repositioned (baseline geometry reset)",
      "دوربین یا دستگاه جابه‌جا شد (بازنشانی هندسه خط پایه)",
      ["camera_moved_event"], ["device_handling", "technical_issue"],
      tier="quality", detector="event", gates=("none",), threshold=1, window_s=5, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1],
      note_en="Posture/gaze baselines are re-estimated after this event.", note_fa="خط پایه وضعیت/نگاه پس از این رویداد دوباره تخمین زده می‌شود."),
    S("glasses_detected", "environment_technical",
      "Glasses detected (gaze/blink precision reduced)",
      "عینک شناسایی شد (دقت نگاه/پلک کاهش می‌یابد)",
      ["glasses_detected"], ["glasses"],
      tier="quality", detector="quality", gates=("none",), threshold=1, min_duration_s=5, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("hands_not_visible", "environment_technical",
      "Hands not visible; hand-based signals suspended",
      "دست‌ها دیده نمی‌شوند؛ سیگنال‌های مبتنی بر دست متوقف شدند",
      ["hands_visible"], ["camera_framing"],
      tier="quality", detector="quality", gates=("none",), threshold=0, min_duration_s=30, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("lower_body_not_visible", "environment_technical",
      "Lower body not visible; leg signals suspended",
      "پایین‌تنه دیده نمی‌شود؛ سیگنال‌های پا متوقف شدند",
      ["lower_body_visible"], ["camera_framing"],
      tier="quality", detector="quality", gates=("none",), threshold=0, min_duration_s=30, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("asr_confidence_low", "environment_technical",
      "Transcript confidence low; language signals suspended",
      "اطمینان رونویسی پایین؛ سیگنال‌های زبانی متوقف شدند",
      ["asr_quality"], ["asr_error", "noise", "language"],
      tier="quality", detector="quality", gates=("none",), threshold=0.7, direction="down", min_duration_s=10, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("baseline_not_ready", "environment_technical",
      "Session baseline not yet established (first minutes)",
      "خط پایه جلسه هنوز ساخته نشده است (دقایق اول)",
      ["face_quality", "pose_quality", "audio_quality"], ["session_phase"],
      tier="quality", detector="quality", gates=("none",), threshold=1, min_duration_s=0, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1],
      note_en="Change-from-baseline signals are disabled until the baseline window (default 5 min of adequate quality) completes.",
      note_fa="سیگنال‌های تغییر نسبت به خط پایه تا تکمیل پنجره خط پایه (پیش‌فرض ۵ دقیقه با کیفیت کافی) غیرفعال هستند."),
    S("baseline_quality_low", "environment_technical",
      "Baseline built on limited or low-quality data",
      "خط پایه بر اساس داده محدود یا کم‌کیفیت ساخته شده است",
      ["face_quality", "pose_quality", "audio_quality"], ["technical_issue", "camera_placement", "lighting"],
      tier="quality", detector="quality", gates=("none",), threshold=0.6, direction="down", min_duration_s=0, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),

    # ------------------------------------------------------------------ operational / consent
    S("analysis_paused_by_patient", "operational",
      "Patient paused behavioral analysis",
      "بیمار تحلیل رفتاری را متوقف کرد",
      [], ["privacy_need"],
      tier="quality", detector="event", gates=("none",), threshold=1, window_s=1, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1],
      note_en="No features are computed or stored while paused. The call continues.", note_fa="در زمان توقف هیچ ویژگی‌ای محاسبه یا ذخیره نمی‌شود. تماس ادامه می‌یابد."),
    S("analysis_resumed_by_patient", "operational",
      "Patient resumed behavioral analysis",
      "بیمار تحلیل رفتاری را از سر گرفت",
      [], ["privacy_need"],
      tier="quality", detector="event", gates=("none",), threshold=1, window_s=1, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
    S("consent_withdrawn", "operational",
      "Patient withdrew analysis consent for the session",
      "بیمار رضایت تحلیل را برای جلسه پس گرفت",
      [], ["privacy_need"],
      tier="quality", detector="event", gates=("none",), threshold=1, window_s=1, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1],
      note_en="All derived features for the session are scheduled for deletion per retention policy.", note_fa="همه ویژگی‌های مشتق‌شده جلسه طبق سیاست نگهداری برای حذف زمان‌بندی می‌شوند."),
    S("clinician_marked_segment", "operational",
      "Clinician manually marked this moment",
      "درمانگر این لحظه را دستی علامت‌گذاری کرد",
      [], ["explicit_content"],
      tier="observation", detector="event", gates=("none",), threshold=1, window_s=1, rationale_en=R_QUAL[0], rationale_fa=R_QUAL[1]),
]
