"""Speech prosody, voice quality, fluency/language, and turn-taking signals."""

from signal_helpers import S

R_PROS = ("Speech rate, pauses, loudness and pitch variability are the audio counterparts of the 'speech' "
          "section of a mental-status observation (rate, volume, prosody). They vary with language, topic, "
          "fatigue, microphone and network conditions; only within-person, network-corrected changes are used.",
          "نرخ گفتار، مکث‌ها، بلندی و تغییرپذیری زیر و بمی، همتای صوتی بخش «گفتار» در مشاهده وضعیت روانی هستند (نرخ، حجم، عروض). "
          "این‌ها با زبان، موضوع، خستگی، میکروفون و شبکه تغییر می‌کنند؛ فقط تغییرات درون‌فردی با تصحیح تأخیر شبکه استفاده می‌شود.")
R_VQ = ("Voice-quality measures (jitter, shimmer, HNR, spectral tilt) are sensitive to physical state "
        "(hydration, illness, fatigue), microphone and codec; they are surfaced as descriptive changes only.",
        "شاخص‌های کیفیت صدا (جیتر، شیمر، HNR، شیب طیفی) به وضعیت جسمی (آب بدن، بیماری، خستگی)، میکروفون و کدک حساس‌اند؛ فقط به‌عنوان تغییرات توصیفی نمایش داده می‌شوند.")
R_LANG = ("Lexical and fluency measures describe how the patient talks (repetitions, self-corrections, "
          "pronoun use, absolutist words). They are content-derived, language-dependent and ASR-error-prone; "
          "they prompt the clinician to look at the transcript, nothing more.",
          "شاخص‌های واژگانی و روانی گفتار توصیف می‌کنند بیمار چگونه صحبت می‌کند (تکرار، خوداصلاحی، ضمیرها، واژگان مطلق‌گرا). "
          "این‌ها از محتوا استخراج می‌شوند، وابسته به زبان و مستعد خطای تشخیص گفتارند؛ صرفاً درمانگر را به بازبینی متن سوق می‌دهند.")
R_TURN = ("Turn-taking dynamics (latency, overlap, silence, speech share) describe the interaction itself; "
          "network delay is the largest confound and must be subtracted.",
          "پویایی نوبت‌گیری (تأخیر، هم‌پوشانی، سکوت، سهم گفتار) خود تعامل را توصیف می‌کند؛ تأخیر شبکه بزرگ‌ترین مخدوش‌کننده است و باید کسر شود.")

SIGNALS = [
    # ------------------------------------------------------------------ prosody: rate & timing
    S("speech_rate_increase", "speech_prosody",
      "Speaking rate increased from baseline",
      "نرخ گفتار نسبت به خط پایه افزایش یافته است",
      ["speech_rate_wpm", "articulation_rate_sps"], ["topic_familiarity", "speech_emphasis", "activation", "urgency", "language"],
      tier="change", gates=("audio", "asr"), direction="up", speaker_state="patient_speaking", window_s=60, rationale_en=R_PROS[0], rationale_fa=R_PROS[1]),
    S("speech_rate_decrease", "speech_prosody",
      "Speaking rate decreased from baseline",
      "نرخ گفتار نسبت به خط پایه کاهش یافته است",
      ["speech_rate_wpm", "articulation_rate_sps"], ["thinking", "fatigue", "word_finding", "topic", "language"],
      tier="change", gates=("audio", "asr"), direction="down", threshold=-2.0, speaker_state="patient_speaking", window_s=60, rationale_en=R_PROS[0], rationale_fa=R_PROS[1]),
    S("articulation_rate_change", "speech_prosody",
      "Syllable rate within phrases changed (independent of pauses)",
      "نرخ هجا درون عبارت‌ها تغییر کرده است (مستقل از مکث)",
      ["articulation_rate_sps", "syllable_duration_mean"], ["language", "fatigue", "activation", "medication"],
      tier="change", gates=("audio",), speaker_state="patient_speaking", window_s=60, rationale_en=R_PROS[0], rationale_fa=R_PROS[1]),
    S("tempo_variability_change", "speech_prosody",
      "Variability of speaking tempo changed from baseline",
      "تغییرپذیری تمپوی گفتار نسبت به خط پایه تغییر کرده است",
      ["tempo_variability"], ["speech_emphasis", "word_finding", "language", "activation"],
      tier="change", gates=("audio",), speaker_state="patient_speaking", window_s=120, rationale_en=R_PROS[0], rationale_fa=R_PROS[1]),
    S("pause_rate_increase", "speech_prosody",
      "Pauses more frequent than baseline",
      "مکث‌ها بیشتر از خط پایه شده‌اند",
      ["pause_count"], ["thinking", "word_finding", "network_latency", "fatigue", "emotional_response"],
      tier="change", detector="rate_change", gates=("audio",), speaker_state="patient_speaking", rationale_en=R_PROS[0], rationale_fa=R_PROS[1],
      note_en="Account for network delay.", note_fa="تأخیر شبکه را در نظر بگیرید."),
    S("pause_duration_increase", "speech_prosody",
      "Pauses longer than baseline",
      "مکث‌ها طولانی‌تر از خط پایه شده‌اند",
      ["pause_duration_mean", "pause_duration_max"], ["thinking", "word_finding", "network_latency", "memory_retrieval", "emotional_response"],
      tier="change", gates=("audio",), direction="up", speaker_state="patient_speaking", window_s=60, rationale_en=R_PROS[0], rationale_fa=R_PROS[1]),
    S("pause_rate_decrease", "speech_prosody",
      "Pauses less frequent than baseline (pressured-like flow)",
      "مکث‌ها کمتر از خط پایه شده‌اند (جریان بی‌وقفه)",
      ["pause_count"], ["topic_familiarity", "urgency", "activation", "speech_emphasis"],
      tier="change", detector="rate_change", gates=("audio",), threshold=0.5, direction="down", speaker_state="patient_speaking", rationale_en=R_PROS[0], rationale_fa=R_PROS[1],
      note_en="Describe as reduced pausing; never auto-label 'pressured speech'.", note_fa="به‌عنوان کاهش مکث توصیف شود؛ هرگز برچسب خودکار «گفتار فشرده» زده نشود."),
    S("filled_pause_rate_change", "speech_prosody",
      "Filled pauses (um / uh / اِ / اوم) changed from baseline",
      "مکث‌های پرشده (اِ، اوم) نسبت به خط پایه تغییر کرده‌اند",
      ["filled_pause_rate"], ["word_finding", "cognitive_effort", "language", "habit"],
      tier="change", detector="rate_change", gates=("asr",), speaker_state="patient_speaking", rationale_en=R_LANG[0], rationale_fa=R_LANG[1]),
    S("mid_utterance_long_pause", "speech_prosody",
      "Long pause in the middle of an utterance",
      "مکث طولانی در میانه یک گفته",
      ["pause_duration_max"], ["word_finding", "memory_retrieval", "distraction", "network_latency", "emotional_response"],
      detector="event", gates=("audio",), threshold=2500, window_s=10, speaker_state="patient_speaking", rationale_en=R_PROS[0], rationale_fa=R_PROS[1]),
    S("response_latency_increase", "speech_prosody",
      "Time from question end to answer start longer than baseline",
      "فاصله پایان سؤال تا شروع پاسخ طولانی‌تر از خط پایه است",
      ["response_latency_ms", "question_event", "network_rtt_ms"], ["thinking", "network_latency", "distraction", "question_type", "memory_retrieval", "topic_related"],
      tier="change", gates=("turn",), direction="up", threshold=2.0, window_s=300, rationale_en=R_TURN[0], rationale_fa=R_TURN[1],
      note_en="Subtract measured network latency; show baseline vs current values.", note_fa="تأخیر اندازه‌گیری‌شده شبکه کسر شود؛ مقدار خط پایه و فعلی نمایش داده شود."),
    S("response_latency_decrease", "speech_prosody",
      "Answers start faster than baseline",
      "پاسخ‌ها سریع‌تر از خط پایه شروع می‌شوند",
      ["response_latency_ms"], ["topic_familiarity", "urgency", "activation", "question_type"],
      tier="change", gates=("turn",), direction="down", threshold=-2.0, window_s=300, rationale_en=R_TURN[0], rationale_fa=R_TURN[1]),
    S("utterance_duration_change", "speech_prosody",
      "Average speaking-turn length changed from baseline",
      "میانگین طول نوبت گفتار نسبت به خط پایه تغییر کرده است",
      ["utterance_duration"], ["question_type", "topic", "interaction_change", "fatigue"],
      tier="change", gates=("turn",), window_s=300, rationale_en=R_TURN[0], rationale_fa=R_TURN[1]),

    # ------------------------------------------------------------------ prosody: loudness & pitch
    S("volume_increase", "speech_prosody",
      "Relative vocal intensity increased",
      "شدت نسبی صدا افزایش یافته است",
      ["loudness_rms_db"], ["microphone", "noise", "speech_emphasis", "activation"],
      tier="change", gates=("audio",), direction="up", speaker_state="patient_speaking", window_s=30, rationale_en=R_PROS[0], rationale_fa=R_PROS[1],
      note_en="Normalize for device/mic gain.", note_fa="برای بهره میکروفون نرمال‌سازی شود."),
    S("volume_decrease", "speech_prosody",
      "Relative vocal intensity decreased",
      "شدت نسبی صدا کاهش یافته است",
      ["loudness_rms_db"], ["microphone", "fatigue", "privacy_need", "low_energy", "emotional_response"],
      tier="change", gates=("audio",), direction="down", threshold=-2.0, speaker_state="patient_speaking", window_s=30, rationale_en=R_PROS[0], rationale_fa=R_PROS[1]),
    S("volume_variability_change", "speech_prosody",
      "Loudness variability changed from baseline",
      "تغییرپذیری بلندی صدا نسبت به خط پایه تغییر کرده است",
      ["loudness_std", "loudness_peak_rate"], ["speech_emphasis", "microphone", "activation", "fatigue"],
      tier="change", gates=("audio",), speaker_state="patient_speaking", window_s=60, rationale_en=R_PROS[0], rationale_fa=R_PROS[1]),
    S("speech_energy_trend_down", "speech_prosody",
      "Loudness trails off across the session",
      "بلندی صدا در طول جلسه رو به کاهش است",
      ["speech_energy_slope"], ["fatigue", "microphone", "session_phase", "low_energy"],
      tier="change", detector="trend", gates=("audio",), direction="down", rationale_en=R_PROS[0], rationale_fa=R_PROS[1]),
    S("pitch_mean_change", "speech_prosody",
      "Mean pitch shifted from baseline",
      "میانگین زیر و بمی نسبت به خط پایه تغییر کرده است",
      ["f0_mean"], ["speech_emphasis", "illness", "activation", "language", "affective_expression"],
      tier="change", gates=("audio",), speaker_state="patient_speaking", window_s=60, rationale_en=R_PROS[0], rationale_fa=R_PROS[1]),
    S("pitch_variability_decrease", "speech_prosody",
      "Pitch variability reduced (flatter intonation)",
      "تغییرپذیری زیر و بمی کاهش یافته (لحن یکنواخت‌تر)",
      ["f0_std", "f0_range"], ["fatigue", "language", "reading", "low_energy", "medication"],
      tier="change", gates=("audio",), direction="down", threshold=-2.0, speaker_state="patient_speaking", window_s=90, rationale_en=R_PROS[0], rationale_fa=R_PROS[1],
      note_en="Describe as reduced intonation range; never 'monotone affect'.", note_fa="به‌عنوان کاهش دامنه لحن توصیف شود؛ نه «عاطفه یکنواخت»."),
    S("pitch_variability_increase", "speech_prosody",
      "Pitch variability increased (more animated intonation)",
      "تغییرپذیری زیر و بمی افزایش یافته (لحن پرتحرک‌تر)",
      ["f0_std", "f0_range"], ["speech_emphasis", "humor", "activation", "affective_expression"],
      tier="change", gates=("audio",), direction="up", speaker_state="patient_speaking", window_s=90, rationale_en=R_PROS[0], rationale_fa=R_PROS[1]),
    S("pitch_range_change", "speech_prosody",
      "Pitch range (p95 - p5) changed from baseline",
      "دامنه زیر و بمی نسبت به خط پایه تغییر کرده است",
      ["f0_range"], ["speech_emphasis", "language", "fatigue", "affective_expression"],
      tier="change", gates=("audio",), speaker_state="patient_speaking", window_s=120, rationale_en=R_PROS[0], rationale_fa=R_PROS[1]),
    S("final_rise_ratio_change", "speech_prosody",
      "Proportion of utterances ending with rising intonation changed",
      "نسبت گفته‌هایی که با لحن بالارونده پایان می‌یابند تغییر کرده است",
      ["f0_slope_final"], ["language", "communication_style", "confusion", "question_type"],
      tier="change", gates=("audio",), speaker_state="patient_speaking", window_s=180, rationale_en=R_PROS[0], rationale_fa=R_PROS[1]),
    S("voiced_ratio_change", "speech_prosody",
      "Proportion of voiced speech changed from baseline",
      "نسبت گفتار واکدار نسبت به خط پایه تغییر کرده است",
      ["voiced_ratio"], ["illness", "microphone", "fatigue", "language"],
      tier="change", gates=("audio",), speaker_state="patient_speaking", window_s=60, rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),

    # ------------------------------------------------------------------ voice quality
    S("jitter_increase", "voice_quality",
      "Cycle-to-cycle pitch perturbation (jitter) increased",
      "لرزش فرکانسی صدا (جیتر) افزایش یافته است",
      ["jitter"], ["illness", "fatigue", "hunger_thirst", "microphone", "emotional_response"],
      tier="change", gates=("audio",), direction="up", speaker_state="patient_speaking", window_s=60, rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),
    S("shimmer_increase", "voice_quality",
      "Cycle-to-cycle amplitude perturbation (shimmer) increased",
      "لرزش دامنه صدا (شیمر) افزایش یافته است",
      ["shimmer"], ["illness", "fatigue", "microphone", "emotional_response"],
      tier="change", gates=("audio",), direction="up", speaker_state="patient_speaking", window_s=60, rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),
    S("hnr_decrease", "voice_quality",
      "Harmonics-to-noise ratio decreased (hoarser / breathier)",
      "نسبت هارمونیک به نویز کاهش یافته (صدای گرفته‌تر یا نفس‌آلودتر)",
      ["hnr", "cpp"], ["illness", "fatigue", "microphone", "noise", "emotional_response"],
      tier="change", gates=("audio",), direction="down", threshold=-2.0, speaker_state="patient_speaking", window_s=60, rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),
    S("voice_tremor_like", "voice_quality",
      "Low-frequency modulation of pitch/amplitude (tremor-like)",
      "مدولاسیون کم‌فرکانس زیر و بمی یا دامنه (شبیه لرزش صدا)",
      ["f0_modulation_hz", "shimmer"], ["emotional_response", "temperature", "medication", "neurological", "illness"],
      tier="medical", detector="periodicity", gates=("audio",), band=(4.0, 8.0), min_duration_s=2, speaker_state="patient_speaking", rationale_en=R_VQ[0], rationale_fa=R_VQ[1],
      note_en="Medical flag; may also accompany strong emotion. Never diagnostic.", note_fa="پرچم پزشکی؛ ممکن است با هیجان شدید هم همراه باشد. هرگز تشخیصی نیست."),
    S("creaky_voice_ratio_change", "voice_quality",
      "Share of creaky / fry phonation changed",
      "سهم صدای خش‌دار (فرای) تغییر کرده است",
      ["creak_ratio"], ["language", "communication_style", "fatigue", "hunger_thirst", "session_phase"],
      tier="change", gates=("audio",), speaker_state="patient_speaking", window_s=120, rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),
    S("breathy_voice_increase", "voice_quality",
      "Breathiness increased from baseline",
      "نفس‌آلود بودن صدا نسبت به خط پایه افزایش یافته است",
      ["breathiness_index", "spectral_tilt"], ["illness", "privacy_need", "fatigue", "microphone", "affective_expression"],
      tier="change", gates=("audio",), direction="up", speaker_state="patient_speaking", window_s=60, rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),
    S("tense_voice_like", "voice_quality",
      "Spectral tilt flattened (tense/pressed phonation proxy)",
      "شیب طیفی مسطح‌تر شده (نماینده صدای فشرده)",
      ["spectral_tilt", "alpha_ratio", "hammarberg_index"], ["speech_emphasis", "noise", "microphone", "activation", "affective_expression"],
      tier="change", gates=("audio",), direction="up", speaker_state="patient_speaking", window_s=60, rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),
    S("voice_break_event", "voice_quality",
      "Voicing break within an utterance",
      "شکست صدا در میانه گفته",
      ["voice_break_event"], ["illness", "hunger_thirst", "network_latency", "emotional_response"],
      detector="event", gates=("audio",), threshold=1, window_s=10, speaker_state="patient_speaking", rationale_en=R_VQ[0], rationale_fa=R_VQ[1],
      note_en="Exclude packet loss first.", note_fa="ابتدا افت بسته شبکه را رد کنید."),
    S("voice_break_rate_change", "voice_quality",
      "Voice breaks more frequent than baseline",
      "شکست صدا بیشتر از خط پایه شده است",
      ["voice_break_event", "packet_loss"], ["illness", "network_latency", "emotional_response", "fatigue"],
      tier="change", detector="rate_change", gates=("audio",), rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),
    S("whisper_like_low_energy_speech", "voice_quality",
      "Very low-energy, low-voicing speech (whisper-like)",
      "گفتار بسیار کم‌انرژی و کم‌واک (شبیه نجوا)",
      ["loudness_rms_db", "voiced_ratio"], ["privacy_need", "other_person", "illness", "microphone", "emotional_response"],
      detector="sustained", gates=("audio",), threshold=-2.5, direction="down", min_duration_s=5, speaker_state="patient_speaking", rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),
    S("formant_shift", "voice_quality",
      "Formant frequencies shifted from baseline (vocal tract posture)",
      "فرکانس فرمانت‌ها نسبت به خط پایه تغییر کرده است",
      ["formant_f1", "formant_f2"], ["language", "posture_habit", "illness", "microphone", "affective_expression"],
      tier="change", gates=("audio",), speaker_state="patient_speaking", window_s=120, rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),
    S("spectral_flux_change", "voice_quality",
      "Rate of spectral change in speech differs from baseline",
      "نرخ تغییر طیفی گفتار با خط پایه متفاوت است",
      ["spectral_flux", "spectral_centroid"], ["language", "speech_emphasis", "microphone", "fatigue"],
      tier="change", gates=("audio",), speaker_state="patient_speaking", window_s=120, rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),

    # ------------------------------------------------------------------ nonverbal vocalizations & breathing
    S("sigh_event", "voice_quality",
      "Sigh-like audible exhalation",
      "بازدم شنیدنی شبیه آه",
      ["sigh_event", "breath_event"], ["breathing", "fatigue", "relief", "thinking", "emotional_response"],
      detector="event", gates=("audio",), threshold=1, window_s=10, rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),
    S("sigh_rate_change", "voice_quality",
      "Sighing more/less frequent than baseline",
      "آه کشیدن بیشتر/کمتر از خط پایه شده است",
      ["sigh_event"], ["breathing", "fatigue", "topic_related", "emotional_response"],
      tier="change", detector="rate_change", gates=("audio",), rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),
    S("audible_breathing_rate_change", "voice_quality",
      "Audible breathing rate changed from baseline",
      "نرخ تنفس شنیدنی نسبت به خط پایه تغییر کرده است",
      ["breath_rate"], ["breathing", "microphone", "illness", "activation", "stretching"],
      tier="change", gates=("audio",), window_s=60, rationale_en=R_VQ[0], rationale_fa=R_VQ[1],
      note_en="Only when mic is close enough to hear breathing; low reliability.", note_fa="فقط وقتی میکروفون به‌اندازه کافی نزدیک باشد؛ اعتماد پایین."),
    S("throat_clear_event", "voice_quality",
      "Throat clearing",
      "صاف کردن گلو",
      ["nonverbal_vocal_event"], ["illness", "habit", "word_finding", "hunger_thirst"],
      detector="event", gates=("audio",), threshold=1, window_s=10, rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),
    S("throat_clear_rate_change", "voice_quality",
      "Throat clearing more frequent than baseline",
      "صاف کردن گلو بیشتر از خط پایه شده است",
      ["nonverbal_vocal_event"], ["illness", "habit", "hunger_thirst", "topic_related"],
      tier="change", detector="rate_change", gates=("audio",), rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),
    S("cough_event", "voice_quality",
      "Cough",
      "سرفه",
      ["nonverbal_vocal_event"], ["illness", "habit", "hunger_thirst"],
      detector="event", gates=("audio",), threshold=1, window_s=10, rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),
    S("laughter_event", "voice_quality",
      "Laughter",
      "خنده",
      ["nonverbal_vocal_event"], ["humor", "politeness", "rapport", "self_soothing", "affective_expression"],
      detector="event", gates=("audio",), threshold=1, window_s=10, rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),
    S("laughter_rate_change", "voice_quality",
      "Laughter more/less frequent than baseline",
      "خنده بیشتر/کمتر از خط پایه شده است",
      ["nonverbal_vocal_event"], ["humor", "rapport", "topic", "politeness", "interaction_change"],
      tier="change", detector="rate_change", gates=("audio",), rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),
    S("laughter_speech_content_mismatch", "voice_quality",
      "Laughter co-occurring with negatively valenced verbal content",
      "خنده هم‌زمان با محتوای کلامی با بار منفی",
      ["nonverbal_vocal_event", "negative_lexicon_ratio"], ["self_soothing", "politeness", "humor", "cultural_norm", "asr_error"],
      detector="event", gates=("audio", "asr"), threshold=1, window_s=8, rationale_en=R_LANG[0], rationale_fa=R_LANG[1],
      note_en="Common and normal; surface only as 'consider'.", note_fa="رایج و طبیعی است؛ فقط به‌عنوان «قابل توجه» نمایش داده شود."),
    S("sob_like_vocalization", "voice_quality",
      "Sob-like or crying-like vocalization detected",
      "صدای شبیه هق‌هق یا گریه شناسایی شد",
      ["nonverbal_vocal_event", "voice_break_event", "breath_event"], ["emotional_response", "illness", "breathing", "noise"],
      detector="event", gates=("audio",), threshold=1, window_s=10, rationale_en=R_VQ[0], rationale_fa=R_VQ[1],
      note_en="Descriptive; clinician can see and hear the patient directly.", note_fa="توصیفی؛ درمانگر خودش بیمار را می‌بیند و می‌شنود."),
    S("sniff_event", "voice_quality",
      "Sniffing",
      "بالا کشیدن بینی",
      ["nonverbal_vocal_event"], ["illness", "temperature", "habit", "emotional_response"],
      detector="event", gates=("audio",), threshold=1, window_s=10, rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),
    S("yawn_audible_event", "voice_quality",
      "Audible yawn",
      "خمیازه شنیدنی",
      ["nonverbal_vocal_event"], ["fatigue", "boredom", "breathing", "session_phase"],
      detector="event", gates=("audio",), threshold=1, window_s=10, rationale_en=R_VQ[0], rationale_fa=R_VQ[1]),

    # ------------------------------------------------------------------ fluency & language
    S("word_repetition_rate_change", "speech_fluency_language",
      "Word/phrase repetitions more frequent than baseline",
      "تکرار واژه/عبارت بیشتر از خط پایه شده است",
      ["repetition_rate"], ["word_finding", "speech_emphasis", "language", "asr_error", "cognitive_effort"],
      tier="change", detector="rate_change", gates=("asr",), rationale_en=R_LANG[0], rationale_fa=R_LANG[1]),
    S("self_correction_rate_change", "speech_fluency_language",
      "Self-corrections more/less frequent than baseline",
      "خوداصلاحی بیشتر/کمتر از خط پایه شده است",
      ["self_correction_rate"], ["word_finding", "cognitive_effort", "language", "asr_error"],
      tier="change", detector="rate_change", gates=("asr",), rationale_en=R_LANG[0], rationale_fa=R_LANG[1]),
    S("incomplete_utterance_increase", "speech_fluency_language",
      "More utterances abandoned mid-sentence than baseline",
      "گفته‌های ناتمام بیشتر از خط پایه شده‌اند",
      ["incomplete_utterance_rate"], ["word_finding", "distraction", "interruption", "emotional_response", "asr_error"],
      tier="change", gates=("asr",), direction="up", window_s=300, rationale_en=R_LANG[0], rationale_fa=R_LANG[1]),
    S("disfluency_rate_change", "speech_fluency_language",
      "Stutter-like disfluencies (sound/syllable repetitions, prolongations) changed",
      "ناروانی‌های شبیه لکنت (تکرار صدا/هجا، کشیدگی) تغییر کرده است",
      ["disfluency_rate"], ["habit", "cognitive_effort", "language", "activation", "asr_error"],
      tier="change", gates=("asr", "audio"), window_s=300, rationale_en=R_LANG[0], rationale_fa=R_LANG[1]),
    S("word_finding_pause_event", "speech_fluency_language",
      "Pause followed by a filler or restart (word-finding-like)",
      "مکث و سپس پرکننده یا شروع دوباره (شبیه جست‌وجوی واژه)",
      ["pause_duration_max", "filled_pause_rate", "self_correction_rate"], ["word_finding", "language", "fatigue", "memory_retrieval"],
      detector="event", gates=("asr", "audio"), threshold=1, window_s=8, rationale_en=R_LANG[0], rationale_fa=R_LANG[1]),
    S("utterance_length_decrease", "speech_fluency_language",
      "Utterances shorter (fewer words) than baseline",
      "گفته‌ها کوتاه‌تر (کلمات کمتر) از خط پایه هستند",
      ["utterance_word_count_mean"], ["question_type", "fatigue", "topic", "low_energy", "discomfort_with_topic"],
      tier="change", gates=("asr",), direction="down", threshold=-2.0, window_s=300, rationale_en=R_LANG[0], rationale_fa=R_LANG[1]),
    S("utterance_length_increase", "speech_fluency_language",
      "Utterances longer than baseline",
      "گفته‌ها طولانی‌تر از خط پایه هستند",
      ["utterance_word_count_mean"], ["question_type", "topic_familiarity", "engagement", "activation"],
      tier="change", gates=("asr",), direction="up", window_s=300, rationale_en=R_LANG[0], rationale_fa=R_LANG[1]),
    S("lexical_diversity_change", "speech_fluency_language",
      "Lexical diversity changed from baseline",
      "تنوع واژگانی نسبت به خط پایه تغییر کرده است",
      ["type_token_ratio"], ["topic", "fatigue", "language", "question_type"],
      tier="change", gates=("asr",), window_s=600, rationale_en=R_LANG[0], rationale_fa=R_LANG[1]),
    S("sentence_complexity_change", "speech_fluency_language",
      "Sentence complexity changed from baseline",
      "پیچیدگی جمله نسبت به خط پایه تغییر کرده است",
      ["sentence_complexity"], ["topic", "fatigue", "language", "question_type", "cognitive_effort"],
      tier="change", gates=("asr",), window_s=600, rationale_en=R_LANG[0], rationale_fa=R_LANG[1]),
    S("first_person_ratio_change", "speech_fluency_language",
      "Use of first-person singular pronouns changed",
      "کاربرد ضمیر اول‌شخص مفرد تغییر کرده است",
      ["first_person_ratio"], ["topic", "question_type", "language", "communication_style"],
      tier="change", gates=("asr",), window_s=600, rationale_en=R_LANG[0], rationale_fa=R_LANG[1],
      note_en="Persian pro-drop makes this noisy; treat as low confidence.", note_fa="حذف ضمیر در فارسی این شاخص را پرنویز می‌کند؛ اعتماد پایین."),
    S("negative_lexicon_ratio_increase", "speech_fluency_language",
      "Higher share of negatively valenced words than baseline",
      "سهم واژگان با بار منفی بیشتر از خط پایه است",
      ["negative_lexicon_ratio"], ["topic", "figure_of_speech", "language", "explicit_content", "asr_error"],
      tier="content", detector="level_change", gates=("asr",), direction="up", window_s=300, rationale_en=R_LANG[0], rationale_fa=R_LANG[1],
      note_en="Lexicon-based; links to transcript segment. Not a mood measure.", note_fa="بر پایه واژه‌نامه؛ به بخش متن پیوند می‌خورد. سنجه خلق نیست."),
    S("positive_lexicon_ratio_change", "speech_fluency_language",
      "Share of positively valenced words changed",
      "سهم واژگان با بار مثبت تغییر کرده است",
      ["positive_lexicon_ratio"], ["topic", "politeness", "figure_of_speech", "language"],
      tier="content", gates=("asr",), window_s=300, rationale_en=R_LANG[0], rationale_fa=R_LANG[1]),
    S("absolutist_word_ratio_increase", "speech_fluency_language",
      "More absolutist words (always / never / completely) than baseline",
      "واژگان مطلق‌گرا (همیشه، هرگز، کاملاً) بیشتر از خط پایه",
      ["absolutist_ratio"], ["speech_emphasis", "figure_of_speech", "topic", "communication_style"],
      tier="content", gates=("asr",), direction="up", window_s=600, rationale_en=R_LANG[0], rationale_fa=R_LANG[1]),
    S("hedging_ratio_change", "speech_fluency_language",
      "Use of hedging words (maybe / I guess / شاید) changed",
      "کاربرد واژگان تردیدآمیز (شاید، فکر کنم) تغییر کرده است",
      ["hedge_ratio", "certainty_ratio"], ["topic_familiarity", "communication_style", "politeness", "cognitive_effort"],
      tier="content", gates=("asr",), window_s=600, rationale_en=R_LANG[0], rationale_fa=R_LANG[1]),
    S("temporal_focus_shift", "speech_fluency_language",
      "Shift in past / present / future tense usage",
      "تغییر در کاربرد زمان گذشته / حال / آینده",
      ["past_tense_ratio", "future_tense_ratio"], ["topic", "question_type", "memory_retrieval", "language"],
      tier="content", gates=("asr",), window_s=600, rationale_en=R_LANG[0], rationale_fa=R_LANG[1]),
    S("minimal_response_to_open_question", "speech_fluency_language",
      "One- or two-word answer to an open question",
      "پاسخ یک یا دو کلمه‌ای به سؤال باز",
      ["minimal_response_flag", "question_event"], ["question_type", "fatigue", "discomfort_with_topic", "communication_style", "confusion"],
      detector="event", gates=("asr", "turn"), threshold=1, window_s=15, rationale_en=R_LANG[0], rationale_fa=R_LANG[1]),
    S("minimal_response_rate_increase", "speech_fluency_language",
      "Minimal answers more frequent than baseline",
      "پاسخ‌های حداقلی بیشتر از خط پایه شده‌اند",
      ["minimal_response_flag"], ["question_type", "fatigue", "discomfort_with_topic", "low_energy", "interaction_change"],
      tier="change", detector="rate_change", gates=("asr", "turn"), rationale_en=R_LANG[0], rationale_fa=R_LANG[1]),
    S("topic_deflection_event", "speech_fluency_language",
      "Answer appears to change the subject (low-confidence language-model judgement)",
      "پاسخ ظاهراً موضوع را عوض می‌کند (قضاوت مدل زبانی با اطمینان پایین)",
      ["deflection_flag", "question_event"], ["confusion", "hearing", "asr_error", "communication_style", "discomfort_with_topic"],
      tier="content", detector="content", gates=("asr",), rationale_en=R_LANG[0], rationale_fa=R_LANG[1],
      note_en="Show the question and answer text side by side; never label 'avoidance'.", note_fa="متن سؤال و پاسخ کنار هم نمایش داده شود؛ هرگز برچسب «اجتناب» زده نشود."),
    S("safety_relevant_phrase", "speech_fluency_language",
      "Explicit safety-relevant phrase in the patient's speech (self-harm, harm to others, abuse)",
      "عبارت صریح مرتبط با ایمنی در گفتار بیمار (آسیب به خود، آسیب به دیگران، آزار)",
      ["risk_lexicon_hit"], ["explicit_content", "figure_of_speech", "asr_error"],
      tier="safety", detector="content", gates=("asr",), rationale_en=(
          "Explicit verbal statements are the only channel through which safety content may be flagged. "
          "The flag simply points the clinician to the exact transcript segment; it carries no risk score."),
      rationale_fa=("اظهارات صریح کلامی تنها کانالی است که از طریق آن محتوای ایمنی می‌تواند پرچم‌گذاری شود. "
                    "پرچم فقط درمانگر را به بخش دقیق متن ارجاع می‌دهد؛ هیچ امتیاز خطری ندارد."),
      note_en="Content flag from transcript only. Never derived from face/body/voice. No risk scoring.",
      note_fa="پرچم محتوا فقط از متن. هرگز از چهره/بدن/صدا استخراج نمی‌شود. هیچ امتیازدهی خطر انجام نمی‌شود."),

    # ------------------------------------------------------------------ turn taking
    S("long_silence", "turn_taking",
      "Silence longer than the session's personal threshold",
      "سکوت طولانی‌تر از آستانه شخصی جلسه",
      ["silence_duration", "network_rtt_ms"], ["thinking", "technical_issue", "distraction", "emotional_response", "question_type"],
      detector="sustained", gates=("turn",), threshold=6, min_duration_s=6, rationale_en=R_TURN[0], rationale_fa=R_TURN[1],
      note_en="Check connection state before surfacing.", note_fa="پیش از نمایش، وضعیت اتصال را بررسی کنید."),
    S("silence_after_question_ratio_change", "turn_taking",
      "More questions followed by long silence than baseline",
      "سؤال‌های بیشتری با سکوت طولانی دنبال می‌شوند",
      ["silence_duration", "question_event"], ["thinking", "question_type", "network_latency", "topic_related"],
      tier="change", gates=("turn",), direction="up", window_s=600, rationale_en=R_TURN[0], rationale_fa=R_TURN[1]),
    S("interruption_overlap", "turn_taking",
      "Overlapping speech / interruption",
      "هم‌پوشانی گفتار / قطع کردن صحبت",
      ["overlap_duration", "speaker"], ["network_latency", "communication_style", "urgency", "cultural_norm"],
      detector="event", gates=("turn",), threshold=600, window_s=5, rationale_en=R_TURN[0], rationale_fa=R_TURN[1],
      note_en="Network latency can create false overlaps.", note_fa="تأخیر شبکه می‌تواند هم‌پوشانی کاذب ایجاد کند."),
    S("interruption_rate_change", "turn_taking",
      "Interruptions more/less frequent than baseline",
      "قطع کردن صحبت بیشتر/کمتر از خط پایه شده است",
      ["overlap_duration"], ["network_latency", "communication_style", "urgency", "interaction_change"],
      tier="change", detector="rate_change", gates=("turn",), rationale_en=R_TURN[0], rationale_fa=R_TURN[1]),
    S("speech_share_change", "turn_taking",
      "Patient's share of speaking time changed from baseline",
      "سهم زمان صحبت بیمار نسبت به خط پایه تغییر کرده است",
      ["speech_share_patient"], ["question_type", "interaction_change", "topic", "fatigue", "session_phase"],
      tier="change", gates=("turn",), window_s=300, rationale_en=R_TURN[0], rationale_fa=R_TURN[1]),
    S("backchannel_rate_change", "turn_taking",
      "Listener feedback sounds (mm-hm, آها) changed from baseline",
      "صداهای بازخورد شنونده (اوهوم، آها) نسبت به خط پایه تغییر کرده‌اند",
      ["backchannel_event"], ["engagement", "communication_style", "cultural_norm", "network_latency", "distraction"],
      tier="change", detector="rate_change", gates=("turn",), speaker_state="patient_listening", rationale_en=R_TURN[0], rationale_fa=R_TURN[1]),
    S("patient_initiated_turn_rate_change", "turn_taking",
      "Patient-initiated turns more/less frequent than baseline",
      "نوبت‌های آغازشده توسط بیمار بیشتر/کمتر از خط پایه",
      ["patient_initiated_turn"], ["engagement", "urgency", "communication_style", "interaction_change"],
      tier="change", detector="rate_change", gates=("turn",), rationale_en=R_TURN[0], rationale_fa=R_TURN[1]),
    S("simultaneous_start_event", "turn_taking",
      "Both parties start speaking at the same time",
      "هر دو طرف هم‌زمان شروع به صحبت می‌کنند",
      ["overlap_duration", "turn_gap_ms"], ["network_latency", "urgency", "communication_style"],
      detector="event", gates=("turn",), threshold=1, window_s=5, rationale_en=R_TURN[0], rationale_fa=R_TURN[1]),
    S("turn_gap_variability_change", "turn_taking",
      "Variability of turn gaps changed from baseline",
      "تغییرپذیری فاصله بین نوبت‌ها نسبت به خط پایه تغییر کرده است",
      ["turn_gap_ms"], ["network_latency", "question_type", "thinking", "interaction_change"],
      tier="change", gates=("turn",), window_s=300, rationale_en=R_TURN[0], rationale_fa=R_TURN[1]),
]
