<?php

return [
    'phq9' => ['Little interest or pleasure in doing things', 'Feeling down, depressed, or hopeless', 'Trouble falling or staying asleep, or sleeping too much', 'Feeling tired or having little energy', 'Poor appetite or overeating', 'Feeling bad about yourself — or that you are a failure', 'Trouble concentrating on things', 'Moving or speaking so slowly that others noticed, or being fidgety/restless', 'Thoughts that you would be better off dead or of hurting yourself'],
    'gad7' => ['Feeling nervous, anxious, or on edge', 'Not being able to stop or control worrying', 'Worrying too much about different things', 'Trouble relaxing', 'Being so restless that it is hard to sit still', 'Becoming easily annoyed or irritable', 'Feeling afraid as if something awful might happen'],
    'pss10' => ['Been upset because of something that happened unexpectedly', 'Felt unable to control the important things in your life', 'Felt nervous and stressed', 'Felt confident about your ability to handle personal problems', 'Felt that things were going your way', 'Found that you could not cope with all the things you had to do', 'Been able to control irritations in your life', 'Felt that you were on top of things', 'Been angered because of things outside your control', 'Felt difficulties were piling up so high you could not overcome them'],
    'isi' => ['Difficulty falling asleep', 'Difficulty staying asleep', 'Problem waking up too early', 'How satisfied are you with your current sleep pattern?', 'How noticeable to others is your sleep problem?', 'How worried are you about your sleep problem?', 'How much does your sleep problem interfere with daily functioning?'],
    'pcl5' => ['Repeated, disturbing memories of the stressful experience', 'Repeated, disturbing dreams', 'Suddenly feeling or acting as if it were happening again', 'Feeling very upset when reminded', 'Strong physical reactions when reminded', 'Avoiding memories, thoughts, or feelings', 'Avoiding external reminders', 'Trouble remembering important parts', 'Strong negative beliefs about yourself, others, or the world', 'Blaming yourself or others', 'Strong negative feelings', 'Loss of interest in activities', 'Feeling distant or cut off', 'Trouble experiencing positive feelings', 'Irritable behaviour or angry outbursts', 'Taking too many risks', 'Being super alert or on guard', 'Feeling jumpy or easily startled', 'Difficulty concentrating', 'Trouble falling or staying asleep'],
    'audit_c' => ['How often do you have a drink containing alcohol?', 'How many drinks do you have on a typical day when drinking?', 'How often do you have six or more drinks on one occasion?'],
];
